/**
 * Comprehensive Crop Cultivation & Agrohomeopathy Database
 * Detailed agronomic requirements, seasonal schedules, cultivation best practices,
 * and homeopathic care plans derived from agrohomeopathy principles.
 */

export const CROP_CATEGORIES = [
  { id: 'ALL', label: 'All Crops' },
  { id: 'VEGETABLE', label: 'Vegetables' },
  { id: 'GRAIN', label: 'Grains & Cereals' },
  { id: 'PULSE', label: 'Pulses & Legumes' },
  { id: 'FRUIT', label: 'Fruits & Orchards' },
  { id: 'CASH', label: 'Cash & Oilseeds' },
  { id: 'SPICE', label: 'Spices & Herbs' },
];

export const SEASONS = [
  { id: 'ALL', label: 'All Seasons' },
  { id: 'Kharif', label: 'Kharif (Monsoon / Autumn)' },
  { id: 'Rabi', label: 'Rabi (Winter / Spring)' },
  { id: 'Zaid', label: 'Zaid (Summer)' },
  { id: 'Perennial', label: 'Year-Round / Perennial' },
];

export const CROPS_DATA = [
  // -------------------------------------------------------------
  // VEGETABLES
  // -------------------------------------------------------------
  {
    id: 'crop_tomato',
    name: 'Tomato',
    hindiName: 'टमाटर (Tamatar)',
    botanicalName: 'Solanum lycopersicum',
    category: 'VEGETABLE',
    season: 'Rabi / Kharif',
    seasonDetails: 'Autumn-Winter (Oct-Feb) in plains; Summer-Rainy (June-Sept) in hills / protected cultivation.',
    duration: '90 - 120 days',
    climate: {
      temperature: '18°C - 28°C (Optimal 21-24°C)',
      sunlight: 'Full Sun (6-8 hours daily)',
      soil: 'Well-drained sandy loam or clay loam rich in organic humus',
      ph: '6.0 - 6.8',
    },
    sowing: {
      method: 'Transplanting (nursery raised 25-30 days seedlings)',
      seedRate: '150 - 200 g / acre (Hybrid: 70 - 90 g / acre)',
      spacing: 'Row-to-Row: 60-75 cm | Plant-to-Plant: 45-60 cm',
      germination: '6 - 10 days',
    },
    growingGuide: {
      soilPrep: 'Deep tilling with 10-15 tonnes well-decomposed FYM or vermicompost per acre. Prepare raised beds with silver-black mulch for moisture conservation.',
      irrigation: 'Drip irrigation every 2-3 days; avoid flood irrigation to prevent collar rot. Water stress during fruit swelling causes skin splitting.',
      practices: 'Provide wooden staking or trellising when plants reach 30 cm. Prune sucker shoots to encourage strong apical growth and large fruit set.',
      harvesting: 'Harvest at breaker stage for distant transport, or vine-ripened red for local consumption. Average yield: 15-25 tonnes/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Soak seeds in Silicea 6X (10 pellets in 1L water) for 4 hours to build resilient seed coats and 100% germination vigor.',
      vegetativeStage: 'Spray Ferrum Phosphoricum 6X + Silicea 6X at 20 days post-transplant for deep chlorophyll development and sturdy main stems.',
      floweringStage: 'Apply Ocymum Basilicum 6X + Calcarea Phosphorica 6X at flower initiation to ensure high calcium uptake and prevent Blossom-End Rot.',
      pestDefense: 'Coccinella Septempunctata 6X for aphids/whiteflies; Sulphur 6X for early/late blight prevention; Helix Tosta 6X perimeter watering for nocturnal slugs.',
      weatherStress: 'Carbo Vegetabilis 6X after extreme heat spells; Aconitum 6X after sudden unseasonal cold/frost.',
    },
  },
  {
    id: 'crop_potato',
    name: 'Potato',
    hindiName: 'आलू (Aloo)',
    botanicalName: 'Solanum tuberosum',
    category: 'VEGETABLE',
    season: 'Rabi',
    seasonDetails: 'October to March (Requires cool night temperatures for tuberization).',
    duration: '90 - 110 days',
    climate: {
      temperature: '15°C - 22°C (Tuber initiation requires 16-20°C)',
      sunlight: 'Full Sun',
      soil: 'Loose, friable sandy loam rich in organic matter',
      ph: '5.2 - 6.5 (Tolerates slightly acidic soil)',
    },
    sowing: {
      method: 'Seed tuber planting (Well-sprouted seed tubers with 2-3 eyes)',
      seedRate: '800 - 1000 kg / acre (Tubers 30-40g each)',
      spacing: 'Row-to-Row: 50-60 cm | Plant-to-Plant: 20-25 cm',
      germination: '10 - 15 days for sprout emergence',
    },
    growingGuide: {
      soilPrep: 'Thorough fine tilth to 20 cm depth. Incorporate rich compost and avoid fresh unrotted manure to prevent scab.',
      irrigation: 'Light and frequent irrigation; keep soil moist but never soggy. Stop irrigation 10-12 days before harvesting.',
      practices: 'Earthing up is crucial at 30 and 45 days after planting to cover developing tubers from sunlight (prevents solanine greening).',
      harvesting: 'Cut vines 10 days before digging to cure and toughen tuber skins. Average yield: 10-18 tonnes/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Dip cut seed tubers in Calendula Officinalis 6X + Arnica Montana 6X (15 pellets in 10L water) for 20 mins to heal tuber cuts and prevent rot.',
      vegetativeStage: 'Spray Silicea 6X at 25 days to fortify haulm cell walls against fungal penetration.',
      floweringStage: 'Phosphorus 6X foliar spray during early tuber initiation to stimulate rapid stolon branching and uniform sizing.',
      pestDefense: 'Carbo Vegetabilis 6X + Sulphur 6X to protect against Late Blight (Phytophthora infestans); Thuja 30C for viral mosaic symptoms.',
      weatherStress: 'Arnica 6X after hail or heavy rain compaction.',
    },
  },
  {
    id: 'crop_onion',
    name: 'Onion & Garlic',
    hindiName: 'प्याज और लहसुन (Pyaz / Lahsun)',
    botanicalName: 'Allium cepa / Allium sativum',
    category: 'VEGETABLE',
    season: 'Rabi / Kharif',
    seasonDetails: 'Rabi (Nov-Dec transplanting for April harvest); Late Kharif (Aug-Sept).',
    duration: '120 - 150 days',
    climate: {
      temperature: '13°C - 24°C vegetative; 25°C - 32°C bulb maturity',
      sunlight: 'Long day / intermediate day sunlight',
      soil: 'Well-drained friable loam or alluvial soil rich in humus',
      ph: '6.0 - 7.5',
    },
    sowing: {
      method: 'Seedling transplanting (Onion) / Cloves planting (Garlic)',
      seedRate: 'Onion: 3 - 4 kg / acre | Garlic: 200 - 250 kg cloves / acre',
      spacing: 'Row-to-Row: 15 cm | Plant-to-Plant: 10 cm',
      germination: '7 - 10 days in nursery',
    },
    growingGuide: {
      soilPrep: 'Fine seedbed with 10 tonnes FYM. Add neem cake to deter root grubs.',
      irrigation: 'Critical at bulb enlargement; irrigate at 7-10 day intervals. Discontinue water when 50% tops fall naturally.',
      practices: 'Keep beds clean of weeds during first 60 days. Avoid deep planting to allow bulbs to expand freely.',
      harvesting: 'Harvest when 70% foliage neck falls over. Field cure for 3-5 days in shade before storage.',
    },
    homeopathyPlan: {
      seedTreatment: 'Silicea 6X root soak prior to transplanting to prevent transplant shock and root dieback.',
      vegetativeStage: 'Ferrum Phosphoricum 6X to accelerate lush vegetative top growth.',
      floweringStage: 'Sulphur 6X + Silicea 6X during bulb initiation to increase pungency, solid dry matter, and storage longevity.',
      pestDefense: 'Thuja Occidentalis 6X for onion thrips (Thrips tabaci) and purple blotch fungus; Coccinella 6X for maggots.',
      weatherStress: 'Carbo Vegetabilis 6X if fields become waterlogged during unseasonal showers.',
    },
  },
  {
    id: 'crop_chilli',
    name: 'Chilli & Bell Pepper (Capsicum)',
    hindiName: 'मिर्च और शिमला मिर्च (Mirch / Shimla Mirch)',
    botanicalName: 'Capsicum annuum / Capsicum frutescens',
    category: 'VEGETABLE',
    season: 'Kharif / Rabi / Summer',
    seasonDetails: 'Year-round cultivation across varying agro-climatic zones.',
    duration: '120 - 180 days (Multiple pickings)',
    climate: {
      temperature: '20°C - 30°C (Sensitive to extreme frost and heavy rainfall during flowering)',
      sunlight: 'Full Sun (Requires bright sunny days for fruit setting)',
      soil: 'Sandy loam to clay loam with excellent drainage',
      ph: '6.0 - 7.0',
    },
    sowing: {
      method: 'Transplanting 30-35 day healthy nursery seedlings',
      seedRate: '200 g / acre (Hybrids: 80 - 100 g / acre)',
      spacing: 'Row-to-Row: 60 cm | Plant-to-Plant: 45 cm',
      germination: '8 - 12 days',
    },
    growingGuide: {
      soilPrep: 'Deep ploughing with 10 tonnes compost. Raised beds with drip irrigation and plastic mulch recommended.',
      irrigation: 'Moderate regular watering. Moisture stress during flowering causes bud and flower drop.',
      practices: 'Nip terminal shoots at 45 days to encourage bushy lateral branching and double the flower nodes.',
      harvesting: 'Harvest green peppers as desired; harvest deep red for drying. Yield: 4-10 tonnes green / 1-2 tonnes dry per acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Calendula Officinalis 6X + Silicea 6X soak for 6 hours to build disease-free sturdy seedlings.',
      vegetativeStage: 'Phosphorus 6X + Ferrum Phos 6X to build vigorous deep root network and heavy lateral branching.',
      floweringStage: 'Belladonna 6X + Ocymum Basilicum 6X to stop flower drop and boost capsaicin development.',
      pestDefense: 'Thuja Occidentalis 30C + Sulphur 6X for Chilli Leaf Curl Virus and yellow mites; Coccinella 6X for thrips/aphids.',
      weatherStress: 'Aconitum 6X after sudden cold winds; Carbo Veg 6X during intense summer heat.',
    },
  },
  {
    id: 'crop_cauliflower_cabbage',
    name: 'Cauliflower & Cabbage (Brassicas)',
    hindiName: 'फूलगोभी और पत्तागोभी (Phoolgobhi / Pattagobhi)',
    botanicalName: 'Brassica oleracea var. botrytis / capitata',
    category: 'VEGETABLE',
    season: 'Rabi / Winter',
    seasonDetails: 'September to February (Early, mid, and late winter varieties).',
    duration: '75 - 100 days from transplanting',
    climate: {
      temperature: '15°C - 20°C (Requires cool temperatures for tight curd/head formation)',
      sunlight: 'Full Sun',
      soil: 'Rich loamy soil with high organic matter and moisture holding capacity',
      ph: '6.0 - 7.5',
    },
    sowing: {
      method: 'Transplanting 25-day nursery seedlings',
      seedRate: '150 - 200 g / acre',
      spacing: 'Row-to-Row: 45-60 cm | Plant-to-Plant: 30-45 cm',
      germination: '5 - 7 days',
    },
    growingGuide: {
      soilPrep: 'Generous incorporation of aged farmyard manure. Boron and molybdenum micronutrients are critical to avoid hollow stem/whiptail.',
      irrigation: 'Uniform soil moisture is vital; drought during curd formation causes loose, yellow, riced curds.',
      practices: 'Blanching (covering white curds with outer leaves) in cauliflower to maintain snowy white color.',
      harvesting: 'Harvest compact, solid curds/heads before loose opening. Yield: 10-18 tonnes/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Silicea 6X seed priming for thick root hair establishment.',
      vegetativeStage: 'Ferrum Phos 6X at 15 days post-transplant for large, broad photosynthesizing outer leaves.',
      floweringStage: 'Calcarea Phosphorica 6X + Silicea 6X during curd initiation for firm, tight, dense curd formation.',
      pestDefense: 'Bombyx Processionea 6X + Thuja 30C to repel Diamondback Moth (DBM) caterpillars and cabbage loopers; Helix Tosta 6X for snails.',
      weatherStress: 'Arnica 6X after severe rainstorms.',
    },
  },

  // -------------------------------------------------------------
  // GRAINS & CEREALS
  // -------------------------------------------------------------
  {
    id: 'crop_wheat',
    name: 'Wheat',
    hindiName: 'गेहूं (Gehun)',
    botanicalName: 'Triticum aestivum',
    category: 'GRAIN',
    season: 'Rabi',
    seasonDetails: 'Sown in November (optimum Nov 10-25) and harvested in March-April.',
    duration: '110 - 140 days',
    climate: {
      temperature: '10°C - 15°C at tillering; 20°C - 25°C at grain filling',
      sunlight: 'Bright sunny days during grain ripening',
      soil: 'Well-drained fertile clay loam or alluvial loam',
      ph: '6.0 - 7.5',
    },
    sowing: {
      method: 'Line sowing with seed drill / broadcasting / Zero-till',
      seedRate: '40 - 50 kg / acre (Bold grain: 50-55 kg / acre)',
      spacing: 'Row-to-Row: 20-22.5 cm | Depth: 4-5 cm',
      germination: '5 - 8 days',
    },
    growingGuide: {
      soilPrep: 'Fine seedbed with 2-3 ploughings. Zero-tillage directly into paddy stubble also highly effective.',
      irrigation: '6 Critical irrigation stages: Crown Root Initiation (CRI at 21 days), Tillering, Jointing, Flowering, Milk stage, Dough stage.',
      practices: 'Timely first irrigation at CRI stage is the most decisive factor for tiller count.',
      harvesting: 'Harvest when grains are hard and moisture drops below 12-14%. Yield: 20-28 quintals/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Silicea 6X (12 pellets per 10L water) seed coating before drilling to promote deep crown root anchoring.',
      vegetativeStage: 'Ferrum Phos 6X + Silicea 6X at CRI stage (21 days) to double effective tiller count and strengthen stem silica content.',
      floweringStage: 'Phosphorus 6X at flag-leaf and ear emergence for long spikelets and complete grain filling.',
      pestDefense: 'Belladonna 6X foliar spray at first sign of yellow/orange stripe rust (Puccinia striiformis); Sulphur 6X for loose smut / powdery mildew.',
      weatherStress: 'Silicea 30C to prevent crop lodging (falling over) during late March wind and hailstorms.',
    },
  },
  {
    id: 'crop_paddy_rice',
    name: 'Paddy Rice',
    hindiName: 'धान / चावल (Dhan / Chawal)',
    botanicalName: 'Oryza sativa',
    category: 'GRAIN',
    season: 'Kharif / Boro (Summer)',
    seasonDetails: 'Kharif (June-July sowing, Oct-Nov harvest); Boro / Summer in irrigated belts.',
    duration: '110 - 150 days (Short to long duration varieties)',
    climate: {
      temperature: '22°C - 32°C (Warm and humid with abundant sunshine)',
      sunlight: 'Full Sun',
      soil: 'Heavy clay or clayey loam that retains water standing',
      ph: '5.5 - 6.5 (Tolerates slightly acidic conditions)',
    },
    sowing: {
      method: 'Puddle transplanting / SRI (System of Rice Intensification) / DSR (Direct Seeded Rice)',
      seedRate: '12 - 15 kg / acre for transplanting (SRI: 2 kg / acre; DSR: 8-10 kg / acre)',
      spacing: '20 cm x 15 cm (SRI: 25 cm x 25 cm square spacing)',
      germination: '3 - 5 days',
    },
    growingGuide: {
      soilPrep: 'Puddling 2-3 times in standing water to create an impervious subsoil layer that holds water.',
      irrigation: 'Maintain 2-5 cm shallow water during tillering and panicle initiation. Drain water 10 days prior to harvest.',
      practices: 'Cono-weeding in SRI method aerates root zone and doubles tiller emergence.',
      harvesting: 'Harvest when 80-85% of panicles turn golden yellow. Average yield: 22-35 quintals/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Soak paddy seeds in Silicea 6X + Calendula 6X solution for 24 hours prior to incubation for zero fungal seed rot.',
      vegetativeStage: 'Ferrum Phosphoricum 6X spray at 25 days to boost photosynthetic rate in standing water.',
      floweringStage: 'Phosphorus 6X at panicle emergence to ensure zero unfilled / chaffy grains at panicle base.',
      pestDefense: 'Coccinella 6X + Thuja 30C for Brown Planthopper (BPH) and Stem Borer; Carbo Veg 6X for Bacterial Leaf Blight (BLB).',
      weatherStress: 'Silicea 6X to harden stem walls against lodging under heavy monsoon rains.',
    },
  },
  {
    id: 'crop_maize',
    name: 'Maize (Corn)',
    hindiName: 'मक्का (Makka)',
    botanicalName: 'Zea mays',
    category: 'GRAIN',
    season: 'Kharif / Rabi / Spring',
    seasonDetails: 'Versatile crop grown in monsoon (Kharif), winter (Rabi in Bihar/AP), and spring.',
    duration: '85 - 110 days',
    climate: {
      temperature: '21°C - 30°C (Requires warm weather and warm soil for emergence)',
      sunlight: 'Full Sun (C4 photosynthesizing plant)',
      soil: 'Deep, rich, well-drained loams with high organic content',
      ph: '6.0 - 7.5',
    },
    sowing: {
      method: 'Ridge and furrow sowing / Dibbling behind plough',
      seedRate: '7 - 8 kg / acre (Sweet corn: 3-4 kg / acre)',
      spacing: 'Row-to-Row: 60 cm | Plant-to-Plant: 20 cm',
      germination: '4 - 6 days',
    },
    growingGuide: {
      soilPrep: 'Deep ploughing with 8 tonnes FYM. Form ridges across slope to avoid waterlogging.',
      irrigation: 'Critical at knee-high stage, tasseling, and silking stages. Highly sensitive to water stagnation.',
      practices: 'Earthing up at knee-high stage (30 days) to strengthen brace roots and support tall stalks.',
      harvesting: 'Harvest when silk turns dark brown and cob husk dries to straw color. Yield: 25-35 quintals/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Silicea 6X seed dressing to trigger early vigorous taproot and prop root emergence.',
      vegetativeStage: 'Ferrum Phos 6X at knee-high stage (30 days) for deep dark green leaf canopy.',
      floweringStage: 'Phosphorus 6X at tasseling & silking to ensure complete grain setting to cob tip.',
      pestDefense: 'Bombyx Processionea 6X + Thuja 30C to protect against Fall Armyworm (Spodoptera frugiperda); Sulphur 6X for downy mildew.',
      weatherStress: 'Carbo Vegetabilis 6X after sudden drought or waterlogged soil stress.',
    },
  },

  // -------------------------------------------------------------
  // PULSES & LEGUMES
  // -------------------------------------------------------------
  {
    id: 'crop_chickpea',
    name: 'Chickpea (Bengal Gram / Chana)',
    hindiName: 'चना (Chana / Desi & Kabuli)',
    botanicalName: 'Cicer arietinum',
    category: 'PULSE',
    season: 'Rabi',
    seasonDetails: 'Sown in October-November in residual soil moisture; harvested in Feb-March.',
    duration: '100 - 120 days',
    climate: {
      temperature: '15°C - 25°C (Cool dry weather; frost at flowering causes severe pod abortion)',
      sunlight: 'Full Sun',
      soil: 'Well-drained sandy loam to black cotton soils with good depth',
      ph: '6.0 - 7.8',
    },
    sowing: {
      method: 'Broadcasting or seed drill line sowing',
      seedRate: 'Desi: 25 - 30 kg / acre | Kabuli: 40 - 45 kg / acre',
      spacing: 'Row-to-Row: 30 cm | Plant-to-Plant: 10 cm | Depth: 6-8 cm',
      germination: '5 - 8 days',
    },
    growingGuide: {
      soilPrep: 'Rough seedbed (avoid too fine a tilth) to retain soil aeration and moisture.',
      irrigation: 'Requires only 1-2 light irrigations (at pre-flowering and pod development). Never flood during peak bloom.',
      practices: 'Nipping / Plucking branch tips at 30-40 days to break apical dominance and trigger dense secondary branching.',
      harvesting: 'Harvest when leaves turn yellow-brown and pods rattle when shaken. Yield: 8-14 quintals/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Silicea 6X + Calendula 6X seed inoculation to stimulate active Rhizobium root nodulation.',
      vegetativeStage: 'Silicea 6X foliar spray at 30 days after nipping to accelerate lateral branch formation.',
      floweringStage: 'Belladonna 6X + Phosphorus 6X to protect flower buds from dropping during sudden temperature spikes.',
      pestDefense: 'Bombyx Processionea 6X to repel Gram Pod Borer (Helicoverpa armigera); Carbo Veg 6X for Fusarium wilt prevention.',
      weatherStress: 'Aconitum 6X immediately following winter frost shock.',
    },
  },
  {
    id: 'crop_pigeonpea',
    name: 'Pigeon Pea (Arhar / Tur Dal)',
    hindiName: 'अरहर / तूर दाल (Arhar / Tur)',
    botanicalName: 'Cajanus cajan',
    category: 'PULSE',
    season: 'Kharif',
    seasonDetails: 'June-July onset of monsoon; harvested in Dec-January.',
    duration: '140 - 180 days (Long duration deep-rooted legume)',
    climate: {
      temperature: '20°C - 35°C (Drought tolerant once deep taproot establishes)',
      sunlight: 'Full Sun',
      soil: 'Deep well-drained loam or alluvial soil without water stagnation',
      ph: '6.5 - 7.5',
    },
    sowing: {
      method: 'Line sowing / Intercropped with Cotton, Soybean, or Maize',
      seedRate: '5 - 6 kg / acre (Solo crop) | 2 - 3 kg / acre (Intercrop)',
      spacing: 'Row-to-Row: 90-120 cm | Plant-to-Plant: 30 cm',
      germination: '5 - 7 days',
    },
    growingGuide: {
      soilPrep: 'Deep tilling to break hard subsoil pan so deep taproot can penetrate 2+ meters.',
      irrigation: 'Primarily rainfed. Life-saving irrigation at pod development if monsoon recedes early.',
      practices: 'Excellent nitrogen fixer that enriches subsequent soil crop rotation.',
      harvesting: 'Harvest when 80% pods dry to brown. Yield: 8-12 quintals/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Silicea 6X to activate rapid taproot downward growth.',
      vegetativeStage: 'Ferrum Phos 6X at 45 days for massive vegetative bushiness.',
      floweringStage: 'Phosphorus 6X + Ocymum 6X at flower initiation for uniform pod set across branches.',
      pestDefense: 'Bombyx Processionea 6X for Pod Borer and Pod Fly (Melanagromyza); Thuja 30C for sterility mosaic virus.',
      weatherStress: 'Carbo Vegetabilis 6X during prolonged dry spells.',
    },
  },

  // -------------------------------------------------------------
  // FRUITS & ORCHARDS
  // -------------------------------------------------------------
  {
    id: 'crop_mango',
    name: 'Mango (King of Fruits)',
    hindiName: 'आम (Aam)',
    botanicalName: 'Mangifera indica',
    category: 'FRUIT',
    season: 'Perennial',
    seasonDetails: 'Flowering: Jan-Feb | Fruit Development: March-May | Harvest: May-July.',
    duration: 'Perennial Orchard (Productive for 40+ years)',
    climate: {
      temperature: '24°C - 30°C (Requires warm dry weather during flowering for pollinator activity)',
      sunlight: 'Full Sun throughout canopy',
      soil: 'Deep rich alluvial or red loamy soil with water table below 2 meters',
      ph: '5.5 - 7.5',
    },
    sowing: {
      method: 'Grafted saplings planting in pits (1m x 1m x 1m filled with FYM & neem cake)',
      seedRate: '40 - 50 trees / acre (Traditional 10m x 10m) | 200 trees / acre (High Density 5m x 4m)',
      spacing: 'Standard: 10m x 10m | High Density: 5m x 3m',
      germination: 'N/A (Vegetative Grafting)',
    },
    growingGuide: {
      soilPrep: 'Dig pits in summer, expose to sunlight, refill with 50 kg compost + 2 kg bone meal + 1 kg neem cake per pit.',
      irrigation: 'Regular drip watering in young trees. Stop irrigation 2 months prior to flowering to induce floral bud differentiation.',
      practices: 'Center pruning (open center system) to let sunlight penetrate inner canopy. Ring weeding under tree basin.',
      harvesting: 'Harvest mature fruits with 1 cm stalk to prevent latex burn on peel. Yield: 4-8 tonnes/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Arnica Montana 6X + Calendula 6X root wash before transplanting grafted sapling to avoid graft mortality.',
      vegetativeStage: 'Silicea 6X tree basin drench post-monsoon for vigorous shoots and bark hardening.',
      floweringStage: 'Belladonna 6X + Phosphorus 6X at panicle emergence to prevent blossom blight, malformation, and flower drop.',
      pestDefense: 'Coccinella 6X + Thuja 30C for Mango Hopper (Idioscopus) and Mealybugs; Sulphur 6X for Powdery Mildew.',
      weatherStress: 'Arnica 6X post annual pruning or storm limb damage.',
    },
  },
  {
    id: 'crop_banana',
    name: 'Banana',
    hindiName: 'केला (Kela)',
    botanicalName: 'Musa acuminata / Grand Naine',
    category: 'FRUIT',
    season: 'Perennial',
    seasonDetails: 'Planting in June-July or Sept-October; harvested 11-13 months later.',
    duration: '11 - 13 months per crop cycle',
    climate: {
      temperature: '20°C - 35°C (Tropical warm humid climate with ample rainfall)',
      sunlight: 'Full Sun (Requires windbreaks to prevent leaf tearing)',
      soil: 'Deep rich loamy soil with good drainage and high organic content',
      ph: '6.5 - 7.5',
    },
    sowing: {
      method: 'Tissue culture plantlets or sword suckers (500-750g)',
      seedRate: '1200 - 1450 plants / acre',
      spacing: '1.8 m x 1.8 m (6ft x 6ft) or 1.5 m x 1.5 m',
      germination: 'Immediate vegetative growth',
    },
    growingGuide: {
      soilPrep: 'Pits of 45 cm cube filled with 10 kg FYM and 250 g neem cake. Drip fertigation network essential.',
      irrigation: 'High water requirement (15-20 Litres/plant/day). Avoid water stagnation around pseudostem.',
      practices: 'De-suckering (removing unwanted side shoots), propping bunches with bamboo poles, and bunch bagging with blue poly-sleeves.',
      harvesting: 'Harvest bunch when ridges on fingers become round and angularity disappears. Yield: 30-45 tonnes/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Calendula 6X sucker dip before planting to prevent Erwinia rhizome rot.',
      vegetativeStage: 'Ferrum Phos 6X + Silicea 6X monthly to build massive pseudostem girth and 14+ functional green leaves.',
      floweringStage: 'Phosphorus 6X at shooting/inflorescence emergence to maximize finger count per hand.',
      pestDefense: 'Cina 6X for Burrowing Nematodes; Carbo Veg 6X for Panama Wilt (Fusarium); Coccinella 6X for banana aphid (bunchy top vector).',
      weatherStress: 'Arnica 6X + Carbo Veg 6X after high windstorm lodging or leaf shredding.',
    },
  },
  {
    id: 'crop_apple',
    name: 'Apple',
    hindiName: 'सेब (Seb)',
    botanicalName: 'Malus domestica',
    category: 'FRUIT',
    season: 'Perennial',
    seasonDetails: 'Winter dormancy (Nov-Feb), Spring flowering (April), Autumn harvest (July-Sept).',
    duration: 'Perennial (Requires 800-1200 chilling hours below 7°C)',
    climate: {
      temperature: '10°C - 24°C in summer; chilling winter dormancy',
      sunlight: 'Full mountain sunshine with good air drainage',
      soil: 'Deep well-drained loamy soil free from heavy subsoil clay',
      ph: '5.5 - 6.8',
    },
    sowing: {
      method: 'Grafted bare-root rootstocks (M9, MM106) planted in winter dormancy (Jan-Feb)',
      seedRate: 'High density (M9): 800 - 1200 trees/acre | Standard: 150 - 200 trees/acre',
      spacing: 'High Density: 3m x 1m | Standard: 5m x 5m',
      germination: 'N/A',
    },
    growingGuide: {
      soilPrep: 'Deep hillside terracing with heavy compost incorporation. Ensure proper pollinizer tree ratio (20-33%).',
      irrigation: 'Drip irrigation during fruit swelling period (May-July) is vital for premium fruit sizing.',
      practices: 'Annual winter pruning, tree training (Spindle bush), and early fruitlet thinning to 1 fruit per cluster.',
      harvesting: 'Harvest when ground color changes from green to pale yellow/red blush. Yield: 8-15 tonnes/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Arnica 6X + Calendula 6X root soak during winter bare-root planting.',
      vegetativeStage: 'Arnica Montana 6X trunk and branch wash immediately after winter pruning to seal cuts and arrest sap bleeding.',
      floweringStage: 'Belladonna 6X at pink bud stage to prevent Apple Scab (Venturia inaequalis) and Stripe Rust.',
      pestDefense: 'Coccinella 6X for Woolly Apple Aphids (Eriosoma lanigerum); Sulphur 6X for Powdery Mildew; Helix Tosta 6X for garden pests.',
      weatherStress: 'Aconitum 6X after sudden spring frosts at blossom time; Arnica 6X after hailstorms.',
    },
  },

  // -------------------------------------------------------------
  // CASH CROPS & OILSEEDS
  // -------------------------------------------------------------
  {
    id: 'crop_cotton',
    name: 'Cotton (White Gold)',
    hindiName: 'कपास (Kapas)',
    botanicalName: 'Gossypium hirsutum',
    category: 'CASH',
    season: 'Kharif',
    seasonDetails: 'Sown in May-June with pre-monsoon; picked Oct to January.',
    duration: '150 - 180 days',
    climate: {
      temperature: '21°C - 30°C (Requires 180-200 frost-free days and warm sun during boll bursting)',
      sunlight: 'Full Sun',
      soil: 'Deep Black Cotton Soil (Vertisols) or fertile alluvial loam with high moisture holding capacity',
      ph: '6.0 - 8.0',
    },
    sowing: {
      method: 'Dibbling seeds on ridges or flat beds',
      seedRate: 'Hybrid: 1.5 - 2 kg / acre | Desi: 4 - 5 kg / acre',
      spacing: 'Row-to-Row: 90-120 cm | Plant-to-Plant: 45-60 cm',
      germination: '4 - 7 days',
    },
    growingGuide: {
      soilPrep: 'Deep summer ploughing to eradicate perennial weeds. Incorporate 5 tonnes FYM per acre.',
      irrigation: 'Critical at square formation, flowering, and boll development. Avoid moisture stress at flowering.',
      practices: 'De-topping (pinching apical buds at 80-90 days) to channel energy into boll development.',
      harvesting: 'Pick clean, fully opened bolls in dry sunny mornings. Average yield: 8-15 quintals seed cotton/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Silicea 6X seed dressing to accelerate early taproot emergence.',
      vegetativeStage: 'Ferrum Phos 6X at 30 days to build broad leaf canopy and numerous sympodial (fruiting) branches.',
      floweringStage: 'Phosphorus 6X + Ocymum 6X at square formation to stop square/flower shedding.',
      pestDefense: 'Bombyx Processionea 6X for Pink Bollworm & American Bollworm; Coccinella 6X + Thuja 30C for Whiteflies & Jassids.',
      weatherStress: 'Carbo Vegetabilis 6X after sudden water stagnation or drought spells.',
    },
  },
  {
    id: 'crop_mustard',
    name: 'Mustard & Rapeseed',
    hindiName: 'सरसों / राई (Sarson / Rai)',
    botanicalName: 'Brassica juncea',
    category: 'CASH',
    season: 'Rabi',
    seasonDetails: 'Sown in October (optimum Oct 5-25); harvested in Feb-March.',
    duration: '100 - 125 days',
    climate: {
      temperature: '10°C - 25°C (Cool climate during growth; warm dry sunny weather during seed ripening)',
      sunlight: 'Full Sun',
      soil: 'Sandy loam to loamy soil with good internal drainage',
      ph: '6.0 - 7.5',
    },
    sowing: {
      method: 'Line sowing with seed drill / broadcasting',
      seedRate: '1.5 - 2 kg / acre',
      spacing: 'Row-to-Row: 30-45 cm | Plant-to-Plant: 10-15 cm | Depth: 2-3 cm',
      germination: '3 - 5 days',
    },
    growingGuide: {
      soilPrep: 'Fine firm seedbed with moisture conserved from monsoon.',
      irrigation: 'Only 2 irrigations needed: 1st at 30 days (flowering) and 2nd at 60 days (pod filling).',
      practices: 'Thinning at 15-20 days after sowing to maintain single healthy plants at 12 cm spacing.',
      harvesting: 'Harvest when 75% siliquae (pods) turn golden-yellow in early morning to prevent pod shattering. Yield: 6-10 quintals/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Silicea 6X seed coating to promote rapid germination and root depth.',
      vegetativeStage: 'Sulphur 6X foliar spray at 25 days to elevate oil content and natural glucosinolate defense.',
      floweringStage: 'Phosphorus 6X at yellow bloom stage for long, well-filled seed siliquae.',
      pestDefense: 'Coccinella Septempunctata 6X is the absolute master remedy against Mustard Aphids (Lipaphis erysimi); Sulphur 6X for white rust.',
      weatherStress: 'Aconitum 6X after sudden winter frost episodes.',
    },
  },

  // -------------------------------------------------------------
  // SPICES & HERBS
  // -------------------------------------------------------------
  {
    id: 'crop_turmeric_ginger',
    name: 'Turmeric & Ginger',
    hindiName: 'हल्दी और अदरक (Haldi / Adrak)',
    botanicalName: 'Curcuma longa / Zingiber officinale',
    category: 'SPICE',
    season: 'Kharif',
    seasonDetails: 'Planting in April-May (pre-monsoon); harvest in Dec-February.',
    duration: '210 - 270 days (7 - 9 months)',
    climate: {
      temperature: '20°C - 35°C (Warm humid tropical climate with partial shade adaptability)',
      sunlight: 'Partial Shade to Full Sun (Thrives under tree canopy / Agroforestry)',
      soil: 'Deep friable loamy soil exceptionally rich in organic humus and free from waterlogging',
      ph: '5.5 - 6.8',
    },
    sowing: {
      method: 'Mother or finger rhizome planting on broad raised beds',
      seedRate: '600 - 800 kg rhizomes / acre',
      spacing: 'Row-to-Row: 45 cm | Plant-to-Plant: 20-25 cm',
      germination: '15 - 25 days for shoot emergence',
    },
    growingGuide: {
      soilPrep: 'Generous 15 tonnes compost per acre. Raised beds of 1.2m width with 30cm furrows.',
      irrigation: 'Keep beds consistently moist but never soggy. Drip irrigation under mulch is ideal.',
      practices: 'Heavy green leaf mulching (3 times: at planting, 40 days, and 80 days) is the secret to gigantic rhizome yield.',
      harvesting: 'Harvest when leaves dry and lodge down completely. Yield: 8-12 tonnes fresh rhizome/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Calendula Officinalis 6X + Silicea 6X rhizome soak for 30 mins before planting to prevent soft rot and boost sprouting.',
      vegetativeStage: 'Ferrum Phos 6X + Silicea 6X at 45 days for massive emerald-green leaf development.',
      floweringStage: 'Sulphur 6X + Calcarea Phos 6X during rhizome swelling (month 4-6) to maximize curcumin content and plump finger sizing.',
      pestDefense: 'Carbo Vegetabilis 6X + Thuja 30C for Rhizome Rot (Pythium) and Leaf Spot; Coccinella 6X for shoot borer.',
      weatherStress: 'Carbo Veg 6X after heavy monsoon waterlogging.',
    },
  },
  {
    id: 'crop_coriander',
    name: 'Coriander (Cilantro / Dhania)',
    hindiName: 'धनिया (Dhania)',
    botanicalName: 'Coriandrum sativum',
    category: 'SPICE',
    season: 'Rabi / Kharif / Year-Round',
    seasonDetails: 'Winter is best for seed crop; year-round for green leaves with shade cloth.',
    duration: '35 - 45 days (Greens) | 85 - 100 days (Seed harvest)',
    climate: {
      temperature: '15°C - 25°C (Cool dry weather prevents premature bolting to flower)',
      sunlight: 'Full Sun to Partial Shade',
      soil: 'Rich loamy soil with good moisture holding capacity',
      ph: '6.0 - 7.5',
    },
    sowing: {
      method: 'Broadcasting or line sowing (Split whole seeds into halves before sowing)',
      seedRate: '8 - 10 kg / acre for seed crop | 15 kg / acre for leaf harvesting',
      spacing: 'Row-to-Row: 20-30 cm | Plant-to-Plant: 5-10 cm',
      germination: '8 - 14 days',
    },
    growingGuide: {
      soilPrep: 'Fine weed-free seedbed enriched with well-rotted vermicompost.',
      irrigation: 'Light spray irrigation immediately after sowing. Keep surface continuously moist until full emergence.',
      practices: 'Multi-cut varieties allow 2-3 cuttings of tender aromatic leaves before leaving for seed setting.',
      harvesting: 'Harvest fresh leaves in morning; harvest seed umbels when turning brownish-yellow. Yield: 4-7 quintals seed/acre.',
    },
    homeopathyPlan: {
      seedTreatment: 'Silicea 6X soak for 4 hours to cut germination time from 14 days down to 6 days.',
      vegetativeStage: 'Ferrum Phos 6X for lush dark green foliage with intense essential oil aroma.',
      floweringStage: 'Phosphorus 6X at umbel flowering for heavy, bold aromatic seed set.',
      pestDefense: 'Sulphur 6X for Powdery Mildew and Stem Gall (Protomyces); Coccinella 6X for aphids.',
      weatherStress: 'Carbo Veg 6X during unexpected hot dry winds to prevent early bolting.',
    },
  },
];
