/**
 * Centralized Multi-Language Translation Dictionary and Localization Utilities
 * Supports: English, Hindi, Gujarati, Marathi, Tamil, Telugu, Kannada, Malayalam, Bengali, Punjabi, Odia, Urdu
 */

export const TRANSLATIONS = {
  // English (Default)
  en: {
    home: "Home",
    crop: "Crops",
    videos: "Videos",
    journal: "Journal",
    productivity: "Productivity",
    tasks: "Tasks",
    activity: "Activity",
    settings: "Settings",

    // Videos
    videoTitle: "Agrohomeopathy & Crop Video Hub",
    videoSubtitle: "Watch masterclasses, remedy potentization guides, and field demonstrations.",
    watchVideo: "Watch Video",
    videoDuration: "Duration",
    allVideos: "All Videos",
    potentizationVideos: "Potentization & Dosage",
    cropCareVideos: "Crop Field Care",
    pestControlVideos: "Pest & Insect Defense",
    soilVitalityVideos: "Soil & Composting",
    masterclassVideos: "Masterclass & Repertory",
    searchVideosPlaceholder: "Search videos by remedy, crop, or topic...",
    featuredMasterclass: "Featured Masterclass",
    keyRemediesCovered: "Remedies Explained",

    // Home Dashboard
    welcomeBack: "Farm Dashboard",
    dashboardSubtitle: "Smart Agrohomeopathy & Crop Cultivation Hub",
    activeSeason: "🌱 Active Season",
    totalCrops: "Total Crops",
    activeTreatments: "Active Treatments",
    healthyPlots: "Healthy / Resolved",
    seasonalAdvisory: "Spray Timing & Advisory",
    bestSprayTime: "Early morning or dusk is optimal for homeopathic foliar misting. Never spray under harsh midday sun.",
    navigationHub: "Farm Navigation Hub",
    cropGuide: "Crops Guide",
    cultivationSubtitle: "Cultivation, seasons & care",
    myJournal: "Field Journal",
    activeTreatmentsSubtitle: "Active treatments & logs",
    repertoryBook: "Diseases & Pests",
    repertorySubtitle: "Pathogens & pests repertory",
    materiaEncyclopedia: "Materia Medica",
    materiaSubtitle: "Homeopathic monographs",
    quickRemedyFinder: "Emergency Symptom Diagnostic",
    openFinder: "Open Finder →",
    featuredCrops: "Featured Seasonal Crops",
    viewAll: "View All",
    recentActivity: "Recent Field Treatments",
    noRecentTreatments: "No active treatments yet. Log a crop treatment from Crop Guide or Journal.",
    agroTipOfTheDay: "Agrohomeopathy Principle",
    duration: "Duration",

    // Crop Names Localization
    crop_tomato: "Tomato",
    crop_potato: "Potato",
    crop_onion: "Onion & Garlic",
    crop_chilli: "Chilli & Capsicum",
    crop_cauliflower_cabbage: "Cauliflower & Cabbage",
    crop_wheat: "Wheat",
    crop_paddy_rice: "Paddy Rice",
    crop_maize: "Maize (Corn)",
    crop_chickpea: "Chickpea (Chana)",
    crop_pigeonpea: "Pigeon Pea (Tur Dal)",
    crop_mango: "Mango",
    crop_banana: "Banana",
    crop_apple: "Apple",
    crop_cotton: "Cotton (White Gold)",
    crop_mustard: "Mustard & Rapeseed",
    crop_turmeric_ginger: "Turmeric & Ginger",
    crop_coriander: "Coriander (Dhania)",

    // Crops Guide
    cropGuideTitle: "Crop Cultivation & Agrohomeopathy",
    cropGuideSubtitle: "Growing seasons, cultivation methods, soil needs, and homeopathic care.",
    searchCropsPlaceholder: "Search crops by name, season, soil, or remedy...",
    bestWayToGrow: "Cultivation & Best Practices",
    growingRequirements: "Growing Requirements",
    homeopathyForCrop: "Homeopathic Care Plan",
    soilAndClimate: "Soil & Climate",
    sowingAndSpacing: "Sowing & Spacing",
    waterAndNutrition: "Water & Irrigation",
    harvestingInfo: "Harvesting & Yield",
    seedTreatment: "Seed Inoculation",
    vegetativeStage: "Vegetative Growth",
    floweringStage: "Flowering & Fruit Set",
    pestDefense: "Pest & Disease Defense",
    weatherStress: "Weather & Stress Recovery",
    doneViewing: "Done Viewing",
    logToJournal: "Log to Journal",

    // Farm & Garden Journal
    farmJournal: "Crop & Health Journal",
    journalDesc: "Track plant observations, symptoms, pests, and homeopathic remedies.",
    newEntry: "New Entry",
    addEntry: "Add Journal Entry",
    cropName: "Crop / Plant Name",
    plotLocation: "Plot / Location",
    issueType: "Issue Type",
    symptoms: "Symptoms / Observation",
    remedy: "Homeopathic Remedy",
    potency: "Potency",
    status: "Status",
    monitoring: "Monitoring",
    underTreatment: "Under Treatment",
    recovering: "Recovering",
    resolved: "Resolved",
    totalEntries: "Total Logs",
    searchJournal: "Search crop, remedy, or symptom...",
    noEntriesFound: "No journal entries found",
    entrySaved: "Journal Entry Saved",
    entryDeleted: "Entry Deleted",
    filterAll: "All Logs",
    filterActive: "Active",
    filterResolved: "Resolved",
    markResolved: "Mark Resolved",
    dosageRecommended: "Recommended Dosage",
    notes: "Notes & Observations",

    // Book Sections & Agrohomeopathy Features
    agroRepertory: "Diseases & Pests",
    materiaMedica: "Materia Medica",
    agroGuide: "Book & Guide",
    quickDiagnostic: "Remedy Finder",
    fieldLogs: "Field Journal",
    bookTitle: "Homoeopathy for Farm and Garden",
    bookAuthor: "Vaikunthanath Das Kaviraj",
    logThisRemedy: "Log into Journal",
    keyIndications: "Key Indications",
    targetPests: "Pathogens & Symptoms",
    dosageInstructions: "Dosage & Application",
    primarySimillimum: "Primary Remedy",
    secondaryRemedies: "Secondary Remedies",
    symptomsAndSigns: "Symptoms & Signs",
    applicationMethod: "Application Method",
    potencyAdvice: "Potency Guidance",
    synergies: "Synergies & Modalities",

    // User & Status Bar
    user: "User",
    noEmail: "No email configured",
    notificationsTitle: "Notifications",

    // Productivity / Tools Screen
    toolsAndUtilities: "Tools & utilities",
    toolsDesc: "A growing set of productivity tools to help you work better.",
    quickNotes: "Quick Notes",
    quickNotesDesc: "Capture ideas, meeting notes, and to-dos on the fly.",
    pomodoroTimer: "Pomodoro Timer",
    pomodoroDesc: "Stay focused with 25-minute work sprints and breaks.",
    habitTracker: "Habit Tracker",
    habitDesc: "Track daily habits and build consistent routines.",
    dailyPlanner: "Daily Planner",
    dailyPlannerDesc: "Schedule blocks, sync reminders, and stay on top of daily milestones.",
    moodDiary: "Mood Diary",
    moodDesc: "Log your mood and spot patterns over time.",
    focusMusic: "Focus Music",
    focusDesc: "Ambient sounds and lo-fi beats for deep work.",
    quotation: "Quotation",
    quotationDesc: "Generate professional quotations and proposals.",
    leadGenerator: "Lead Generator",
    leadGeneratorDesc: "Find and generate business leads from Google Maps.",
    open: "Open",
    comingSoon: "Coming soon",

    // Tasks / Kanban
    pipeline: "PIPELINE",
    kanbanBoard: "Kanban Board",
    manageTasksAcrossColumns: "Manage tasks across your workspace columns.",
    loadingWorkspace: "Loading workspace...",

    // Activity
    recent: "RECENT",
    auditTrailDesc: "Cross-module audit trail of key events and actions.",

    // Settings Screen
    accountDetails: "Account Details",
    email: "Email",
    notifications: "Notifications",
    notificationsDesc: "Product updates, comments, mentions",
    security: "Security",
    securityDesc: "2-step verification enabled",
    experience: "Experience",
    workspace: "Workspace",
    pushNotifications: "Push notifications",
    emailUpdates: "Email updates",
    autoSyncDrafts: "Auto sync drafts",
    usageAnalytics: "Usage analytics",
    experimentalFeatures: "Experimental features",
    controlPreview: "Control for settings tab preview.",
    sharedPreferences: "Shared Preferences",
    sharedPreferencesDesc: "View and manage stored app data",
    appearance: "Appearance",
    appearanceDesc: "Switch between light and dark mode.",
    light: "Light",
    dark: "Dark",

    // Language Selection
    language: "Language",
    languageSubtitle: "Language / भाषा",
    selectLanguage: "Select Language",
    selectLanguageTitle: "Select Language / भाषा चुनें",
    chooseLanguageSub: "Choose your preferred regional language",
    searchLanguage: "Search language (Hindi, Tamil, ગુજરાતી...)",
    change: "Change",
    allLanguages: "All Languages",
    southIndianLangs: "South Indian (4)",
    hindiAndNorth: "Hindi & North",
    gujaratiAndMarathi: "Gujarati & Marathi",
    englishLang: "English",
    noLanguageFound: 'No language found for "{query}"',
    languageUpdated: "Language Updated",
    languageSetTo: "App language set to {native} ({name})",

    // Logout Modal
    logout: "Logout",
    logoutConfirmTitle: "Log Out of Devlomatix?",
    logoutConfirmMessage: "You will need to sign back in to access your workspace.",
    cancel: "Cancel",

    // Auth Screens
    emailPlaceholder: "name@company.com",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    forgotPassword: "Forgot password?",
    signIn: "Sign In",
    signingIn: "Signing in...",
    or: "OR",
    continueWithGoogle: "Continue with Google",
    connectingGoogle: "Connecting Google...",
    createNewAccount: "Create new account",
    fullName: "Full Name",
    enterFullName: "Enter your full name",
    confirmPassword: "Confirm Password",
    reEnterPassword: "Re-enter your password",
    alreadyHaveAccount: "Already have an account?",
    signUp: "Sign Up",
    creatingAccount: "Creating account...",
    resetPassword: "Reset Password",
    sendResetLink: "Send Reset Link",
    backToLogin: "Back to Login",
    verifyEmail: "Verify Email",
    enterOtp: "Enter the verification code",
    verify: "Verify",
    resendCode: "Resend Code",

    // Common UI
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    discard: "Discard",
    useText: "Use text",
    close: "Close",
    back: "Back",
    apply: "Apply",
    search: "Search",
    refresh: "Refresh Data",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    applied: "Applied",
    nothingToImprove: "Nothing to improve",
    typeMessageFirst: "Type a message first.",
    aiAssistant: "AI Assistant",
    userData: "User Data",
    workspaceId: "Workspace ID",
    accessToken: "Access Token",
    deviceToken: "Device Token",
    expoPushToken: "Expo Push Token",
    appLanguage: "App Language",
    themeMode: "Theme Mode",
    backToSettings: "Back to Settings",
    saveCurrentUserData: "Save Current User Data",
  },

  // Hindi (हिन्दी)
  hi: {
    home: "होम",
    crop: "फसलें",
    videos: "वीडियो",
    journal: "जर्नल",
    productivity: "उत्पादकता",
    tasks: "कार्य",
    activity: "गतिविधि",
    settings: "सेटिंग्स",

    // Videos
    videoTitle: "एग्रोहोम्योपैथी और फसल वीडियो केंद्र",
    videoSubtitle: "मास्टरक्लास, शक्तिवर्धन विधियां और प्रायोगिक वीडियो देखें।",
    watchVideo: "वीडियो देखें",
    videoDuration: "अवधि",
    allVideos: "सभी वीडियो",
    potentizationVideos: "जल शक्तिवर्धन व खुराक",
    cropCareVideos: "फसल रोग प्रबंधन",
    pestControlVideos: "कीट व इल्ली नियंत्रण",
    soilVitalityVideos: "मृदा व कंपोस्ट सुधार",
    masterclassVideos: "मास्टरक्लास व निर्देशिका",
    searchVideosPlaceholder: "दवा, फसल या विषय द्वारा खोजें...",
    featuredMasterclass: "प्रमुख मास्टरक्लास",
    keyRemediesCovered: "मुख्य दवाएं",

    welcomeBack: "फार्म डैशबोर्ड",
    dashboardSubtitle: "स्मार्ट एग्रोहोम्योपैथी और फसल प्रबंधन केंद्र",
    activeSeason: "🌱 सक्रिय मौसम",
    totalCrops: "कुल फसलें",
    activeTreatments: "सक्रिय उपचार",
    healthyPlots: "स्वस्थ / ठीक",
    seasonalAdvisory: "छिड़काव का समय और सलाह",
    bestSprayTime: "होम्योपैथिक छिड़काव के लिए सुबह या शाम का समय सबसे अच्छा है। तेज धूप में छिड़काव न करें।",
    navigationHub: "फार्म नेविगेशन केंद्र",
    cropGuide: "फसल गाइड",
    cultivationSubtitle: "खेती, मौसम और देखभाल",
    myJournal: "खेत जर्नल",
    activeTreatmentsSubtitle: "सक्रिय उपचार और रिकॉर्ड",
    repertoryBook: "रोग और कीट",
    repertorySubtitle: "रोगज़नक़ और कीट निर्देशिका",
    materiaEncyclopedia: "मटेरिया मेडिका",
    materiaSubtitle: "होम्योपैथिक मोनोग्राफ",
    quickRemedyFinder: "आपातकालीन लक्षण निदान",
    openFinder: "खोजें →",
    featuredCrops: "प्रमुख मौसमी फसलें",
    viewAll: "सभी देखें",
    recentActivity: "हाल के खेत उपचार",
    noRecentTreatments: "अभी कोई सक्रिय उपचार नहीं है। फसल गाइड या जर्नल से जोड़ें।",
    agroTipOfTheDay: "एग्रोहोम्योपैथी सिद्धांत",
    duration: "अवधि",

    // Crop Names
    crop_tomato: "टमाटर",
    crop_potato: "आलू",
    crop_onion: "प्याज और लहसुन",
    crop_chilli: "मिर्च और शिमला मिर्च",
    crop_cauliflower_cabbage: "फूलगोभी और पत्तागोभी",
    crop_wheat: "गेहूं",
    crop_paddy_rice: "धान / चावल",
    crop_maize: "मक्का",
    crop_chickpea: "चना (देसी व काबुली)",
    crop_pigeonpea: "अरहर / तूर दाल",
    crop_mango: "आम",
    crop_banana: "केला",
    crop_apple: "सेब",
    crop_cotton: "कपास",
    crop_mustard: "सरसों / राई",
    crop_turmeric_ginger: "हल्दी और अदरक",
    crop_coriander: "धनिया",

    cropGuideTitle: "फसल उत्पादन और एग्रोहोम्योपैथी",
    cropGuideSubtitle: "फसल चक्र, बुवाई के तरीके, मिट्टी की आवश्यकता और होम्योपैथिक देखभाल।",
    searchCropsPlaceholder: "फसल का नाम, मौसम, मिट्टी या उपचार खोजें...",
    bestWayToGrow: "खेती के सर्वोत्तम तरीके",
    growingRequirements: "उगाने की आवश्यकताएं",
    homeopathyForCrop: "होम्योपैथिक उपचार योजना",
    soilAndClimate: "मिट्टी और जलवायु",
    sowingAndSpacing: "बुवाई और दूरी",
    waterAndNutrition: "सिंचाई और पोषण",
    harvestingInfo: "कटाई और पैदावार",
    seedTreatment: "बीज उपचार",
    vegetativeStage: "वानस्पतिक वृद्धि",
    floweringStage: "फूल और फल निर्माण",
    pestDefense: "कीट और रोग सुरक्षा",
    weatherStress: "मौसम और तनाव से बचाव",
    doneViewing: "पूर्ण हुआ",
    logToJournal: "जर्नल में दर्ज करें",

    farmJournal: "फसल और स्वास्थ्य जर्नल",
    journalDesc: "पौधों के लक्षण, कीटों और होम्योपैथिक उपचारों को दर्ज करें।",
    newEntry: "नया रिकॉर्ड",
    addEntry: "जर्नल प्रविष्टि जोड़ें",
    cropName: "फसल / पौधे का नाम",
    plotLocation: "प्लॉट / स्थान",
    issueType: "समस्या का प्रकार",
    symptoms: "लक्षण / अवलोकन",
    remedy: "होम्योपैथिक उपचार",
    potency: "पोटेंसी",
    status: "स्थिति",
    monitoring: "निगरानी",
    underTreatment: "उपचाराधीन",
    recovering: "सुधार हो रहा है",
    resolved: "समाधान हुआ",
    totalEntries: "कुल रिकॉर्ड",
    searchJournal: "फसल, उपचार या लक्षण खोजें...",
    noEntriesFound: "कोई जर्नल रिकॉर्ड नहीं मिला",
    entrySaved: "जर्नल प्रविष्टि सहेजी गई",
    entryDeleted: "रिकॉर्ड हटाया गया",
    filterAll: "सभी",
    filterActive: "सक्रिय",
    filterResolved: "समाधान",
    markResolved: "ठीक चिह्नित करें",
    dosageRecommended: "अनुशंसित खुराक",
    notes: "टिप्पणियाँ और विवरण",

    agroRepertory: "रोग और कीट",
    materiaMedica: "मटेरिया मेडिका",
    agroGuide: "पुस्तक और मार्गदर्शिका",
    quickDiagnostic: "उपचार खोजक",
    fieldLogs: "खेत जर्नल",
    bookTitle: "खेत और बगीचे के लिए होम्योपैथी",
    bookAuthor: "वैकुंठनाथ दास कविराज",
    logThisRemedy: "जर्नल में दर्ज करें",
    keyIndications: "प्रमुख संकेत",
    targetPests: "लक्षित कीट व रोग",
    dosageInstructions: "खुराक और अनुप्रयोग",
    primarySimillimum: "प्राथमिक उपचार",
    secondaryRemedies: "द्वितीयक उपचार",
    symptomsAndSigns: "लक्षण और संकेत",
    applicationMethod: "अनुप्रयोग विधि",
    potencyAdvice: "पोटेंसी मार्गदर्शन",
    synergies: "पूरक उपचार",

    user: "उपयोगकर्ता",
    noEmail: "कोई ईमेल कॉन्फ़िगर नहीं है",
    notificationsTitle: "सूचनाएं",

    toolsAndUtilities: "उपकरण और सुविधाएं",
    toolsDesc: "बेहतर काम करने में आपकी मदद करने वाले उत्पादकता उपकरण।",
    quickNotes: "त्वरित नोट्स",
    quickNotesDesc: "विचार, मीटिंग नोट्स और कार्य तुरंत दर्ज करें।",
    pomodoroTimer: "पोमोडोरो टाइमर",
    pomodoroDesc: "25 मिनट के कार्य और ब्रेक के साथ एकाग्र रहें।",
    habitTracker: "आदत ट्रैकर",
    habitDesc: "दैनिक आदतों को ट्रैक करें और निरंतर दिनचर्या बनाएं।",
    dailyPlanner: "दैनिक योजनाकार",
    dailyPlannerDesc: "ब्लॉक शेड्यूल करें और मील के पत्थर हासिल करें।",
    moodDiary: "मूड डायरी",
    moodDesc: "अपना मूड लॉग करें और पैटर्न देखें।",
    focusMusic: "फोकस संगीत",
    focusDesc: "गहन कार्य के लिए शांत ध्वनियां और संगीत।",
    quotation: "कोटेशन",
    quotationDesc: "पेशेवर कोटेशन और प्रस्ताव बनाएं।",
    leadGenerator: "लीड जनरेटर",
    leadGeneratorDesc: "गूगल मैप्स से व्यावसायिक लीड खोजें।",
    open: "खोलें",
    comingSoon: "जल्द आ रहा है",

    pipeline: "पाइपलाइन",
    kanbanBoard: "कानबन बोर्ड",
    manageTasksAcrossColumns: "अपने कार्यक्षेत्र कॉलम में कार्यों को प्रबंधित करें।",
    loadingWorkspace: "कार्यक्षेत्र लोड हो रहा है...",

    recent: "हालिया",
    auditTrailDesc: "प्रमुख घटनाओं और कार्रवाइयों का ऑडिट विवरण।",

    accountDetails: "खाता विवरण",
    email: "ईमेल",
    notifications: "सूचनाएं",
    notificationsDesc: "उत्पाद अपडेट, टिप्पणियां, उल्लेख",
    security: "सुरक्षा",
    securityDesc: "2-चरणीय सत्यापन सक्षम है",
    experience: "अनुभव",
    workspace: "कार्यक्षेत्र",
    pushNotifications: "पुश सूचनाएं",
    emailUpdates: "ईमेल अपडेट",
    autoSyncDrafts: "ड्राफ्ट ऑटो सिंक",
    usageAnalytics: "उपयोग विश्लेषण",
    experimentalFeatures: "प्रायोगिक सुविधाएं",
    controlPreview: "सेटिंग्स पूर्वावलोकन नियंत्रण।",
    sharedPreferences: "साझा प्राथमिकताएं",
    sharedPreferencesDesc: "सहेजे गए ऐप डेटा को देखें और प्रबंधित करें",
    appearance: "दिखावट",
    appearanceDesc: "लाइट और डार्क मोड के बीच बदलें।",
    light: "लाइट",
    dark: "डार्क",

    language: "भाषा",
    languageSubtitle: "भाषा / Language",
    selectLanguage: "भाषा चुनें",
    selectLanguageTitle: "भाषा चुनें / Select Language",
    chooseLanguageSub: "अपनी पसंदीदा क्षेत्रीय भाषा चुनें",
    searchLanguage: "भाषा खोजें (हिन्दी, தமிழ், ગુજરાતી...)",
    change: "बदलें",
    allLanguages: "सभी भाषाएं",
    southIndianLangs: "दक्षिण भारतीय (4)",
    hindiAndNorth: "हिन्दी और उत्तर",
    gujaratiAndMarathi: "गुजराती और मराठी",
    englishLang: "अंग्रेज़ी",
    noLanguageFound: '"{query}" के लिए कोई भाषा नहीं मिली',
    languageUpdated: "भाषा अपडेट हो गई",
    languageSetTo: "ऐप की भाषा बदलकर {native} ({name}) कर दी गई है",

    logout: "लॉग आउट",
    logoutConfirmTitle: "Devlomatix से लॉग आउट करें?",
    logoutConfirmMessage: "अपने कार्यक्षेत्र तक पहुंचने के लिए आपको फिर से साइन इन करना होगा।",
    cancel: "रद्द करें",

    emailPlaceholder: "name@company.com",
    password: "पासवर्ड",
    passwordPlaceholder: "अपना पासवर्ड दर्ज करें",
    forgotPassword: "पासवर्ड भूल गए?",
    signIn: "साइन इन करें",
    signingIn: "साइन इन हो रहा है...",
    or: "या",
    continueWithGoogle: "गूगल से जारी रखें",
    connectingGoogle: "गूगल से कनेक्ट हो रहा है...",
    createNewAccount: "नया खाता बनाएं",
    fullName: "पूरा नाम",
    enterFullName: "अपना पूरा नाम दर्ज करें",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    reEnterPassword: "अपना पासवर्ड दोबारा दर्ज करें",
    alreadyHaveAccount: "पहले से खाता है?",
    signUp: "साइन अप करें",
    creatingAccount: "खाता बनाया जा रहा है...",
    resetPassword: "पासवर्ड रीसेट करें",
    sendResetLink: "रीसेट लिंक भेजें",
    backToLogin: "लॉगिन पर वापस जाएं",
    verifyEmail: "ईमेल सत्यापित करें",
    enterOtp: "सत्यापन कोड दर्ज करें",
    verify: "सत्यापित करें",
    resendCode: "कोड दोबारा भेजें",

    save: "सहेजें",
    edit: "संपादित करें",
    delete: "हटाएं",
    discard: "खारिज करें",
    useText: "टेक्स्ट का उपयोग करें",
    close: "बंद करें",
    back: "वापस",
    apply: "लागू करें",
    search: "खोजें",
    refresh: "डेटा रीफ़्रेश करें",
    loading: "लोड हो रहा है...",
    error: "त्रुटि",
    success: "सफलता",
    applied: "लागू किया गया",
    nothingToImprove: "सुधार के लिए कुछ नहीं है",
    typeMessageFirst: "पहले एक संदेश लिखें।",
    aiAssistant: "एआई सहायक",
    userData: "उपयोगकर्ता डेटा",
    workspaceId: "कार्यक्षेत्र आईडी",
    accessToken: "एक्सेस टोकन",
    deviceToken: "डिवाइस टोकन",
    expoPushToken: "एक्सपो पुश टोकन",
    appLanguage: "ऐप की भाषा",
    themeMode: "थीम मोड",
    backToSettings: "सेटिंग्स पर वापस जाएं",
    saveCurrentUserData: "वर्तमान उपयोगकर्ता डेटा सहेजें",
  },

  // Gujarati (ગુજરાતી)
  gu: {
    home: "હોમ",
    crop: "પાક",
    videos: "વિડિઓઝ",
    journal: "જર્નલ",
    productivity: "ઉત્પાદકતા",
    tasks: "કાર્યો",
    activity: "પ્રવૃત્તિ",
    settings: "સેટિંગ્સ",

    welcomeBack: "ફાર્મ ડેશબોર્ડ",
    dashboardSubtitle: "સ્માર્ટ એગ્રોહોમિયોપેથી અને પાક વ્યવસ્થાપન",
    activeSeason: "🌱 સક્રિય સીઝન",
    totalCrops: "કુલ પાક",
    activeTreatments: "સક્રિય સારવાર",
    healthyPlots: "સ્વસ્થ / સુધરેલ",
    seasonalAdvisory: "છંટકાવ સમય અને સલાહ",
    bestSprayTime: "હોમિયોપેથિક છંટકાવ સવારે અથવા સાંજે કરવો ઉત્તમ છે. બપોરના તડકામાં છંટકાવ ન કરવો.",
    navigationHub: "ફાર્મ નેવિગેશન હબ",
    cropGuide: "પાક માર્ગદર્શિકા",
    cultivationSubtitle: "ખેતી, ઋતુ અને સંભાળ",
    myJournal: "ખેત જર્નલ",
    activeTreatmentsSubtitle: "સક્રિય સારવાર અને લોગ",
    repertoryBook: "રોગો અને જીવાતો",
    repertorySubtitle: "રોગકારક અને જીવાત રેપર્ટરી",
    materiaEncyclopedia: "મટેરિયા મેડિકા",
    materiaSubtitle: "હોમિયોપેથિક મોનોગ્રાફ",
    quickRemedyFinder: "તાત્કાલિક લક્ષણ નિદાન",
    openFinder: "શોધો →",
    featuredCrops: "મુખ્ય મોસમી પાક",
    viewAll: "બધા જુઓ",
    recentActivity: "તાજેતરની ખેત સારવાર",
    noRecentTreatments: "હજી સુધી કોઈ સક્રિય સારવાર નથી.",
    agroTipOfTheDay: "એગ્રોહોમિયોપેથી સિદ્ધાંત",
    duration: "સમયગાળો",

    // Crop Names
    crop_tomato: "ટામેટા",
    crop_potato: "બટાટા",
    crop_onion: "ડુંગળી અને લસણ",
    crop_chilli: "મરચાં અને કેપ્સિકમ",
    crop_cauliflower_cabbage: "ફૂલકોબી અને કોબીજ",
    crop_wheat: "ઘઉં",
    crop_paddy_rice: "ડાંગર / ચોખા",
    crop_maize: "મકાઈ",
    crop_chickpea: "ચણા",
    crop_pigeonpea: "તુવેર દાળ",
    crop_mango: "કેરી",
    crop_banana: "કેળાં",
    crop_apple: "સફરજન",
    crop_cotton: "કપાસ",
    crop_mustard: "રાઈ / સરસવ",
    crop_turmeric_ginger: "હળદર અને આદુ",
    crop_coriander: "ધાણા / કોથમીર",

    cropGuideTitle: "પાક ઉત્પાદન અને એગ્રોહોમિયોપેથી",
    cropGuideSubtitle: "પાકની ઋતુઓ, વાવેતર પદ્ધતિ, જમીનની જરૂરિયાત અને હોમિયોપેથિક સંભાળ.",
    searchCropsPlaceholder: "પાકનું નામ, ઋતુ, જમીન અથવા ઉપાય શોધો...",
    bestWayToGrow: "વાવેતરની શ્રેષ્ઠ રીતો",
    growingRequirements: "ઉગાડવાની જરૂરિયાતો",
    homeopathyForCrop: "હોમિયોપેથિક સંભાળ યોજના",
    soilAndClimate: "જમીન અને આબોહવા",
    sowingAndSpacing: "વાવણી અને અંતર",
    waterAndNutrition: "સિંચાઈ અને પોષણ",
    harvestingInfo: "કાપણી અને ઉપજ",
    seedTreatment: "બીજ માવજત",
    vegetativeStage: "વાનસ્પતિક વૃદ્ધિ",
    floweringStage: "ફૂલ અને ફળ નિર્માણ",
    pestDefense: "જીવાત અને રોગ રક્ષણ",
    weatherStress: "હવામાન તણાવ નિવારણ",
    doneViewing: "પૂર્ણ",
    logToJournal: "જર્નલમાં ઉમેરો",

    farmJournal: "પાક અને આરોગ્ય જર્નલ",
    journalDesc: "છોડના લક્ષણો, જીવાતો અને હોમિયોપેથિક ઉપાયો નોંધો.",
    newEntry: "નવો રેકોર્ડ",
    addEntry: "જર્નલ નોંધ ઉમેરો",
    cropName: "પાક / છોડનું નામ",
    plotLocation: "પ્લોટ / સ્થળ",
    issueType: "સમસ્યાનો પ્રકાર",
    symptoms: "લક્ષણો / નિરીક્ષણ",
    remedy: "હોમિયોપેથિક ઉપાય",
    potency: "પોટેન્સી",
    status: "સ્થિતિ",
    monitoring: "દેખરેખ",
    underTreatment: "સારવાર હેઠળ",
    recovering: "સુધરી રહ્યું છે",
    resolved: "ઉકેલાઈ ગયું",
    totalEntries: "કુલ રેકોર્ડ",
    searchJournal: "પાક, ઉપાય અથવા લક્ષણ શોધો...",
    noEntriesFound: "કોઈ જર્નલ રેકોર્ડ મળ્યો નથી",
    entrySaved: "જર્નલ નોંધ સચવાઈ",
    entryDeleted: "નોંધ કાઢી નાખી",
    filterAll: "બધા",
    filterActive: "સક્રિય",
    filterResolved: "ઉકેલાયેલ",
    markResolved: "સંપૂર્ણ ચિહ્નિત કરો",
    dosageRecommended: "ભલામણ કરેલ માત્રા",
    notes: "નોંધ અને વિગતો",

    agroRepertory: "રોગો અને જીવાતો",
    materiaMedica: "મટેરિયા મેડિકા",
    agroGuide: "પુસ્તક અને માર્ગદર્શિકા",
    quickDiagnostic: "ઉપાય શોધક",
    fieldLogs: "ખેત જર્નલ",
    bookTitle: "ખેતર અને બગીચા માટે હોમિયોપેથી",
    bookAuthor: "વૈકુંઠનાથ દાસ કવિરાજ",
    logThisRemedy: "જર્નલમાં ઉમેરો",
    keyIndications: "મુખ્ય સંકેતો",
    targetPests: "લક્ષિત જીવાતો અને રોગો",
    dosageInstructions: "માત્રા અને પદ્ધતિ",
    primarySimillimum: "મુખ્ય ઉપાય",
    secondaryRemedies: "ગૌણ ઉપાયો",
    symptomsAndSigns: "લક્ષણો અને ચિહ્નો",
    applicationMethod: "ઉપયોગ પદ્ધતિ",
    potencyAdvice: "પોટેન્સી માર્ગદર્શન",
    synergies: "પૂરક ઉપાયો",

    user: "વપરાશકર્તા",
    noEmail: "કોઈ ઈમેલ નથી",
    notificationsTitle: "સૂચનાઓ",
    accountDetails: "ખાતાની વિગતો",
    email: "ઈમેલ",
    notifications: "સૂચનાઓ",
    notificationsDesc: "પ્રોડક્ટ અપડેટ્સ, ટિપ્પણીઓ",
    security: "સુરક્ષા",
    securityDesc: "2-પગલાંની ચકાસણી સક્ષમ છે",
    experience: "અનુભવ",
    workspace: "કાર્યસ્થળ",
    pushNotifications: "પુશ સૂચનાઓ",
    emailUpdates: "ઈમેલ અપડેટ્સ",
    autoSyncDrafts: "ડ્રાફ્ટ ઓટો સિંક",
    appearance: "દેખાવ",
    appearanceDesc: "લાઇટ અને ડાર્ક મોડ વચ્ચે બદલો.",
    light: "લાઇટ",
    dark: "ડાર્ક",
    language: "ભાષા",
    languageSubtitle: "ભાષા / Language",
    selectLanguage: "ભાષા પસંદ કરો",
    selectLanguageTitle: "ભાષા પસંદ કરો / Select Language",
    chooseLanguageSub: "તમારી પસંદગીની પ્રાદેશિક ભાષા પસંદ કરો",
    searchLanguage: "ભાષા શોધો (ગુજરાતી, हिन्दी, English...)",
    change: "બદલો",
    allLanguages: "બધી ભાષાઓ",
    southIndianLangs: "દક્ષિણ ભારતીય (4)",
    hindiAndNorth: "હિન્દી અને ઉત્તર",
    gujaratiAndMarathi: "ગુજરાતી અને મરાઠી",
    englishLang: "અંગ્રેજી",
    noLanguageFound: '"{query}" માટે કોઈ ભાષા મળી નથી',
    languageUpdated: "ભાષા અપડેટ થઈ ગઈ",
    languageSetTo: "એપ્લિકેશન ભાષા {native} ({name}) સેટ થઈ ગઈ છે",
    logout: "લૉગ આઉટ",
    logoutConfirmTitle: "Devlomatix માંથી લૉગ આઉટ કરવું છે?",
    logoutConfirmMessage: "તમારા કાર્યસ્થળને ઍક્સેસ કરવા માટે તમારે ફરીથી સાઇન ઇન કરવું પડશે.",
    cancel: "રદ કરો",
    save: "સાચવો",
    edit: "સંપાદિત કરો",
    delete: "કાઢી નાખો",
    discard: "રદ કરો",
    close: "બંધ કરો",
    back: "પાછળ",
    apply: "લાગુ કરો",
    search: "શોધો",
    refresh: "ડેટા તાજો કરો",
    loading: "લોડ થઈ રહ્યું છે...",
    error: "ભૂલ",
    success: "સફળતા",
  },

  // Marathi (मराठी)
  mr: {
    home: "होम",
    crop: "पिके",
    videos: "व्हिडिओ",
    journal: "जर्नल",
    productivity: "उत्पादकता",
    tasks: "कामे",
    activity: "हालचाली",
    settings: "सेटिंग्ज",

    welcomeBack: "शेतकरी डॅशबोर्ड",
    dashboardSubtitle: "स्मार्ट ॲग्रोहोमिओपॅथी आणि पीक व्यवस्थापन",
    activeSeason: "🌱 चालू हंगाम",
    totalCrops: "एकूण पिके",
    activeTreatments: "सक्रिय उपचार",
    healthyPlots: "निरोगी / बरे झालेले",
    seasonalAdvisory: "फवारणीची वेळ आणि सल्ला",
    bestSprayTime: "होमिओपॅथिक फवारणीसाठी सकाळची किंवा संध्याकाळची वेळ सर्वोत्तम आहे. कडक उन्हात फवारणी करू नका.",
    navigationHub: "फार्म नेव्हिगेशन हब",
    cropGuide: "पीक मार्गदर्शक",
    cultivationSubtitle: "शेती, हंगाम आणि निगा",
    myJournal: "शेत डायरी",
    activeTreatmentsSubtitle: "सक्रिय उपचार आणि नोंदी",
    repertoryBook: "रोग आणि कीड",
    repertorySubtitle: "रोग आणि कीटक निर्देशिका",
    materiaEncyclopedia: "मटेरिया मेडिका",
    materiaSubtitle: "होमिओपॅथिक मोनोग्राफ",
    quickRemedyFinder: "तातडीचे लक्षण निदान",
    openFinder: "शोधा →",
    featuredCrops: "प्रमुख हंगामी पिके",
    viewAll: "सर्व पहा",
    recentActivity: "अलीकडील शेतातील उपचार",
    noRecentTreatments: "सध्या कोणतेही सक्रिय उपचार नाहीत.",
    agroTipOfTheDay: "ॲग्रोहोमिओपॅथी तत्त्व",
    duration: "कालावधी",

    // Crop Names
    crop_tomato: "टोमॅटो",
    crop_potato: "बटाटा",
    crop_onion: "कांदा आणि लसूण",
    crop_chilli: "मिरची आणि ढोबळी मिरची",
    crop_cauliflower_cabbage: "फुलकोबी आणि कोबी",
    crop_wheat: "गहू",
    crop_paddy_rice: "भात / तांदूळ",
    crop_maize: "मका",
    crop_chickpea: "हरभरा / चणा",
    crop_pigeonpea: "तूर डाळ",
    crop_mango: "आंबा",
    crop_banana: "केळी",
    crop_apple: "सफरचंद",
    crop_cotton: "कापूस",
    crop_mustard: "मोहरी / सरसो",
    crop_turmeric_ginger: "हळद आणि आले",
    crop_coriander: "धने / कोथिंबीर",

    cropGuideTitle: "पीक लागवड आणि ॲग्रोहोमिओपॅथी",
    cropGuideSubtitle: "पिकांचे हंगाम, लागवड पद्धती, जमिनीची गरज आणि होमिओपॅथिक काळजी.",
    searchCropsPlaceholder: "पिकाचे नाव, हंगाम, जमीन किंवा उपाय शोधा...",
    bestWayToGrow: "लागवडीच्या सर्वोत्तम पद्धती",
    growingRequirements: "वाढीसाठी आवश्यक बाबी",
    homeopathyForCrop: "होमिओपॅथिक काळजी योजना",
    soilAndClimate: "जमीन आणि हवामान",
    sowingAndSpacing: "पेरणी आणि अंतर",
    waterAndNutrition: "पाणी आणि पोषण",
    harvestingInfo: "काढणी आणि उत्पादन",
    seedTreatment: "बीजप्रक्रिया",
    vegetativeStage: "शाकीय वाढ",
    floweringStage: "फुल आणि फळधारणा",
    pestDefense: "कीड आणि रोग संरक्षण",
    weatherStress: "हवामान ताण निवारण",
    doneViewing: "पूर्ण झाले",
    logToJournal: "जर्नलमध्ये नोंदवा",

    farmJournal: "पीक आणि आरोग्य जर्नल",
    journalDesc: "वनस्पतींची लक्षणे, कीड आणि होमिओपॅथिक उपचार नोंदवा.",
    newEntry: "नवीन नोंद",
    addEntry: "जर्नल नोंद जोडा",
    cropName: "पिकाचे / झाडाचे नाव",
    plotLocation: "प्लॉट / जागा",
    issueType: "समस्येचा प्रकार",
    symptoms: "लक्षणे / निरीक्षण",
    remedy: "होमिओपॅथिक औषध",
    potency: "पोटेन्सी",
    status: "स्थिती",
    monitoring: "निरीक्षण चालू",
    underTreatment: "उपचार सुरू",
    recovering: "सुधारणा होत आहे",
    resolved: "बरे झाले",
    totalEntries: "एकूण नोंदी",
    searchJournal: "पीक, औषध किंवा लक्षण शोधा...",
    noEntriesFound: "कोणत्याही नोंदी आढळल्या नाहीत",
    entrySaved: "जर्नल नोंद जतन झाली",
    entryDeleted: "नोंद हटवली",
    filterAll: "सर्व",
    filterActive: "सक्रिय",
    filterResolved: "निकाली",
    markResolved: "बरे झाले म्हणून चिन्हांकित करा",
    dosageRecommended: "शिफारस केलेले प्रमाण",
    notes: "नोंदी आणि निरीक्षणे",

    agroRepertory: "रोग आणि कीड",
    materiaMedica: "मटेरिया मेडिका",
    agroGuide: "पुस्तक आणि मार्गदर्शक",
    quickDiagnostic: "उपाय शोधक",
    fieldLogs: "शेत डायरी",
    bookTitle: "शेती आणि बागेसाठी होमिओपॅथी",
    bookAuthor: "वैकुंठनाथ दास कविराज",
    logThisRemedy: "जर्नलमध्ये नोंदवा",
    keyIndications: "प्रमुख संकेत",
    targetPests: "लक्षित कीड आणि रोग",
    dosageInstructions: "डोस आणि वापर पद्धत",
    primarySimillimum: "प्राथमिक औषध",
    secondaryRemedies: "दुय्यम औषधे",
    symptomsAndSigns: "लक्षणे आणि चिन्हे",
    applicationMethod: "वापरण्याची पद्धत",
    potencyAdvice: "पोटेन्सी मार्गदर्शन",
    synergies: "पूरक औषधे",

    user: "वापरकर्ता",
    noEmail: "ईमेल नाही",
    notificationsTitle: "सूचना",
    accountDetails: "खाते तपशील",
    email: "ईमेल",
    notifications: "सूचना",
    notificationsDesc: "उत्पादन अद्यतने, टिप्पण्या",
    security: "सुरक्षा",
    securityDesc: "2-चरण पडताळणी सक्षम आहे",
    experience: "अनुभव",
    workspace: "कार्यक्षेत्र",
    pushNotifications: "पुश सूचना",
    emailUpdates: "ईमेल अद्यतने",
    appearance: "दिसणे",
    appearanceDesc: "लाइट आणि डार्क मोड बदला.",
    light: "लाइट",
    dark: "डार्क",
    language: "भाषा",
    languageSubtitle: "भाषा / Language",
    selectLanguage: "भाषा निवडा",
    selectLanguageTitle: "भाषा निवडा / Select Language",
    chooseLanguageSub: "आपली पसंतीची प्रादेशिक भाषा निवडा",
    searchLanguage: "भाषा शोधा (मराठी, हिन्दी, English...)",
    change: "बदला",
    allLanguages: "सर्व भाषा",
    southIndianLangs: "दक्षिण भारतीय (4)",
    hindiAndNorth: "हिंदी आणि उत्तर",
    gujaratiAndMarathi: "गुजराती आणि मराठी",
    englishLang: "इंग्रजी",
    noLanguageFound: '"{query}" साठी भाषा सापडली नाही',
    languageUpdated: "भाषा अद्यतनित झाली",
    languageSetTo: "ॲप भाषा {native} ({name}) वर सेट केली आहे",
    logout: "लॉग आउट",
    logoutConfirmTitle: "Devlomatix मधून बाहेर पडायचे?",
    logoutConfirmMessage: "आपल्या कार्यक्षेत्रात प्रवेश करण्यासाठी आपल्याला पुन्हा साइन इन करावे लागेल.",
    cancel: "रद्द करा",
    save: "जतन करा",
    edit: "संपादित करा",
    delete: "हटवा",
    close: "बंद करा",
    back: "मागे",
    apply: "लागू करा",
    search: "शोधा",
    refresh: "डेटा रीफ्रेश करा",
    loading: "लोड होत आहे...",
    error: "त्रुटी",
    success: "यशस्वी",
  },

  // Tamil (தமிழ்)
  ta: {
    home: "முகப்பு",
    crop: "பயிர்கள்",
    videos: "வீடியோக்கள்",
    journal: "ஜர்னல்",
    productivity: "உற்பத்தித்திறன்",
    tasks: "பணிகள்",
    activity: "செயல்பாடு",
    settings: "அமைப்புகள்",

    welcomeBack: "பண்ணை கட்டுப்பாட்டகம்",
    dashboardSubtitle: "ஸ்மார்ட் அக்ரோஹோமியோபதி மற்றும் பயிர் மேலாண்மை மையம்",
    activeSeason: "🌱 தற்போதைய பருவம்",
    totalCrops: "மொத்த பயிர்கள்",
    activeTreatments: "செயலில் உள்ள சிகிச்சைகள்",
    healthyPlots: "ஆரோக்கியமான / குணமடைந்தவை",
    seasonalAdvisory: "தெளிப்பு நேரம் மற்றும் வழிகாட்டுதல்",
    bestSprayTime: "ஹோமியோபதி தெளிப்புக்கு அதிகாலை அல்லது அந்தி சாயும் நேரமே சிறந்தது. கடுமையான வெயிலில் தெளிக்காதீர்கள்.",
    navigationHub: "பண்ணை வழிசெலுத்தல் மையம்",
    cropGuide: "பயிர் வழிகாட்டி",
    cultivationSubtitle: "சாகுபடி, பருவம் மற்றும் பராமரிப்பு",
    myJournal: "பண்ணை ஜர்னல்",
    activeTreatmentsSubtitle: "செயலில் உள்ள சிகிச்சைகள் & பதிவுகள்",
    repertoryBook: "நோய்கள் & பூச்சிகள்",
    repertorySubtitle: "நோய்க்கிருமிகள் மற்றும் பூச்சிகள் வழிகாட்டி",
    materiaEncyclopedia: "மெட்டீரியா மெடிகா",
    materiaSubtitle: "ஹோமியோபதி விளக்கவுரை",
    quickRemedyFinder: "அவசர அறிகுறி கண்டறிதல்",
    openFinder: "கண்டறியவும் →",
    featuredCrops: "முக்கிய பருவப் பயிர்கள்",
    viewAll: "அனைத்தையும் பார்",
    recentActivity: "சமீபத்திய பண்ணை சிகிச்சைகள்",
    noRecentTreatments: "செயலில் உள்ள சிகிச்சைகள் எதுவும் இல்லை.",
    agroTipOfTheDay: "அக்ரோஹோமியோபதி கோட்பாடு",
    duration: "கால அளவு",

    // Crop Names
    crop_tomato: "தக்காளி",
    crop_potato: "உருளைக்கிழங்கு",
    crop_onion: "வெங்காயம் & பூண்டு",
    crop_chilli: "மிளகாய் & குடைமிளகாய்",
    crop_cauliflower_cabbage: "காலிஃபிளவர் & முட்டைக்கோஸ்",
    crop_wheat: "கோதுமை",
    crop_paddy_rice: "நெல் / அரிசி",
    crop_maize: "மக்காச்சோளம்",
    crop_chickpea: "கொண்டைக்கடலை",
    crop_pigeonpea: "துவரம் பருப்பு",
    crop_mango: "மாம்பழம்",
    crop_banana: "வாழைப்பழம்",
    crop_apple: "ஆப்பிள்",
    crop_cotton: "பருத்தி",
    crop_mustard: "கடுகு",
    crop_turmeric_ginger: "மஞ்சள் & இஞ்சி",
    crop_coriander: "கொத்தமல்லி",

    cropGuideTitle: "பயிர் சாகுபடி மற்றும் அக்ரோஹோமியோபதி",
    cropGuideSubtitle: "பயிர் பருவங்கள், விதைப்பு முறைகள், மண் தேவைகள் மற்றும் ஹோமியோபதி பராமரிப்பு.",
    searchCropsPlaceholder: "பயிர் பெயர், பருவம், மண் அல்லது மருந்து தேடுங்கள்...",
    bestWayToGrow: "சிறந்த சாகுபடி முறைகள்",
    growingRequirements: "வளர்ச்சித் தேவைகள்",
    homeopathyForCrop: "ஹோமியோபதி பராமரிப்பு திட்டம்",
    soilAndClimate: "மண் மற்றும் தட்பவெப்பநிலை",
    sowingAndSpacing: "விதைப்பு மற்றும் இடைவெளி",
    waterAndNutrition: "நீர்ப்பாசனம் மற்றும் ஊட்டச்சத்து",
    harvestingInfo: "அறுவடை மற்றும் மகசூல்",
    seedTreatment: "விதை நேர்த்தி",
    vegetativeStage: "தாவர வளர்ச்சி",
    floweringStage: "பூக்கும் மற்றும் காய் பிடிக்கும் நிலை",
    pestDefense: "பூச்சி மற்றும் நோய் பாதுகாப்பு",
    weatherStress: "வானிலை அழுத்த மீட்பு",
    doneViewing: "பார்த்து முடிந்தது",
    logToJournal: "ஜர்னலில் சேர்",

    farmJournal: "பயிர் மற்றும் சுகாதார ஜர்னல்",
    journalDesc: "தாவர அறிகுறிகள், பூச்சிகள் மற்றும் ஹோமியோபதி மருந்துகளைப் பதிவு செய்யுங்கள்.",
    newEntry: "புதிய பதிவு",
    addEntry: "ஜர்னல் பதிவு சேர்க்கவும்",
    cropName: "பயிர் / தாவரத்தின் பெயர்",
    plotLocation: "பகுதி / இடம்",
    issueType: "பிரச்சனை வகை",
    symptoms: "அறிகுறிகள் / அவதானிப்பு",
    remedy: "ஹோமியோபதி மருந்து",
    potency: "வீரியம் (Potency)",
    status: "நிலை",
    monitoring: "கண்காணிப்பு",
    underTreatment: "சிகிச்சையில் உள்ளது",
    recovering: "குணமடைந்து வருகிறது",
    resolved: "குணமடைந்தது",
    totalEntries: "மொத்த பதிவுகள்",
    searchJournal: "பயிர், மருந்து அல்லது அறிகுறி தேடுங்கள்...",
    noEntriesFound: "ஜர்னல் பதிவுகள் எதுவும் இல்லை",
    entrySaved: "ஜர்னல் பதிவு சேமிக்கப்பட்டது",
    entryDeleted: "பதிவு நீக்கப்பட்டது",
    filterAll: "அனைத்தும்",
    filterActive: "செயலில் உள்ளவை",
    filterResolved: "குணமடைந்தவை",
    markResolved: "குணமடைந்ததாகக் குறிக்கவும்",
    dosageRecommended: "பரிந்துரைக்கப்பட்ட அளவு",
    notes: "குறிப்புகள்",

    agroRepertory: "நோய்கள் & பூச்சிகள்",
    materiaMedica: "மெட்டீரியா மெடிகா",
    agroGuide: "புத்தகம் மற்றும் வழிகாட்டி",
    quickDiagnostic: "மருந்து கண்டுபிடிப்பான்",
    fieldLogs: "பண்ணை ஜர்னல்",
    bookTitle: "பண்ணை மற்றும் தோட்டத்திற்கான ஹோமியோபதி",
    bookAuthor: "வைகுண்டநாத் தாஸ் கவிராஜ்",
    logThisRemedy: "ஜர்னலில் பதிவு செய்க",

    user: "பயனர்",
    language: "மொழி",
    languageSubtitle: "மொழி / Language",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    selectLanguageTitle: "மொழியைத் தேர்ந்தெடுக்கவும் / Select Language",
    chooseLanguageSub: "விருப்பமான மொழியைத் தேர்வுசெய்யவும்",
    searchLanguage: "மொழியைத் தேடுங்கள்...",
    change: "மாற்று",
    allLanguages: "அனைத்து மொழிகள்",
    southIndianLangs: "தென்னிந்திய மொழிகள் (4)",
    hindiAndNorth: "இந்தி & வடக்கு",
    gujaratiAndMarathi: "குஜராத்தி & மராத்தி",
    englishLang: "ஆங்கிலம்",
    logout: "வெளியேறு",
    cancel: "ரத்து செய்",
    save: "சேமி",
    edit: "திருத்து",
    delete: "நீக்கு",
    close: "மூடு",
    back: "பின்செல்",
    apply: "பயன்படுத்து",
    search: "தேடு",
    loading: "ஏற்றுகிறது...",
    success: "வெற்றி",
  },

  // Telugu (తెలుగు)
  te: {
    home: "హోమ్",
    crop: "పంటలు",
    videos: "వీడియోలు",
    journal: "జర్నల్",
    productivity: "ఉత్పాదకత",
    tasks: "టాస్క్‌లు",
    activity: "కార్యాచరణ",
    settings: "సెట్టింగ్‌లు",

    welcomeBack: "రైతు డాష్‌బోర్డ్",
    dashboardSubtitle: "స్మార్ట్ ఆగ్రోహోమియోపతి మరియు పంట యాజమాన్య కేంద్రం",
    activeSeason: "🌱 ప్రస్తుత సీజన్",
    totalCrops: "మొత్తం పంటలు",
    activeTreatments: "చికిత్సలో ఉన్నవి",
    healthyPlots: "ఆరోగ్యవంతమైనవి / నయమైనవి",
    seasonalAdvisory: "పిచికారీ సమయం & సలహా",
    bestSprayTime: "హోమియోపతి పిచికారీకి ఉదయం లేదా సాయంత్రం వేళ ఉత్తమం. ఎండలో పిచికారీ చేయవద్దు.",
    navigationHub: "పంట కేంద్రం",
    cropGuide: "పంటల గైడ్",
    cultivationSubtitle: "సాగు, సీజన్లు & సంరక్షణ",
    myJournal: "పొలం జర్నల్",
    activeTreatmentsSubtitle: "చికిత్సలు మరియు లాగ్‌లు",
    repertoryBook: "తెగుళ్లు & పురుగులు",
    repertorySubtitle: "తెగుళ్ల నివారణ గైడ్",
    materiaEncyclopedia: "మెటీరియా మెడికా",
    materiaSubtitle: "హోమియోపతి ఔషధ వివరణ",
    quickRemedyFinder: "అత్యవసర లక్షణ నిర్ధారణ",
    openFinder: "వెతకండి →",
    featuredCrops: "ముఖ్యమైన సీజనల్ పంటలు",
    viewAll: "అన్నీ చూడండి",
    recentActivity: "ఇటీవలి పంట చికిత్సలు",
    noRecentTreatments: "చికిత్సలో ఉన్నవి ఏవీ లేవు.",
    agroTipOfTheDay: "ఆగ్రోహోమియోపతి సూత్రం",
    duration: "వ్యవధి",

    // Crop Names
    crop_tomato: "టమోటా",
    crop_potato: "బంగాళాదుంప",
    crop_onion: "ఉల్లిపాయ & వెల్లుల్లి",
    crop_chilli: "మిరప & క్యాప్సికమ్",
    crop_cauliflower_cabbage: "క్యాలీఫ్లవర్ & క్యాబేజీ",
    crop_wheat: "గోధుమలు",
    crop_paddy_rice: "వరి / బియ్యం",
    crop_maize: "మొక్కజొన్న",
    crop_chickpea: "శనగలు",
    crop_pigeonpea: "కందిపప్పు",
    crop_mango: "మామిడి",
    crop_banana: "అరటిపండు",
    crop_apple: "యాపిల్",
    crop_cotton: "పత్తి",
    crop_mustard: "ఆవాలు",
    crop_turmeric_ginger: "పసుపు & అల్లం",
    crop_coriander: "ధనియాలు / కొత్తిమీర",

    cropGuideTitle: "పంట సాగు మరియు ఆగ్రోహోమియోపతి",
    cropGuideSubtitle: "పంట కాలాలు, విత్తే పద్ధతులు, నేల అవసరాలు మరియు హోమియోపతి సంరక్షణ.",
    searchCropsPlaceholder: "పంట పేరు, కాలం, నేల లేదా ఔషధం వెతకండి...",
    bestWayToGrow: "ఉత్తమ సాగు పద్ధతులు",
    growingRequirements: "సాగు అవసరాలు",
    homeopathyForCrop: "హోమియోపతి సంరక్షణ ప్రణాళిక",
    soilAndClimate: "నేల మరియు వాతావరణం",
    sowingAndSpacing: "విత్తనం మరియు దూరం",
    waterAndNutrition: "నీటిపారుదల మరియు పోషణ",
    harvestingInfo: "కోత మరియు దిగుబడి",
    seedTreatment: "విత్తన శుద్ధి",
    vegetativeStage: "శాకీయ పెరుగుదల",
    floweringStage: "పూత మరియు కాత దశ",
    pestDefense: "పురుగులు మరియు తెగుళ్ల రక్షణ",
    weatherStress: "వాతావరణ ఒత్తిడి నివారణ",
    doneViewing: "పూర్తయింది",
    logToJournal: "జర్నల్‌లో నమోదు చేయండి",

    farmJournal: "పంట & ఆరోగ్య జర్నల్",
    journalDesc: "మొక్కల లక్షణాలు, పురుగులు మరియు హోమియోపతి చికిత్సలను నమోదు చేయండి.",
    newEntry: "కొత్త నమోదు",
    addEntry: "జర్నల్ నమోదు జోడించండి",
    cropName: "పంట / మొక్క పేరు",
    plotLocation: "పొలం / స్థలం",
    issueType: "సమస్య రకం",
    symptoms: "లక్షణాలు / పరిశీలన",
    remedy: "హోమియోపతి ఔషధం",
    potency: "పొటెన్సీ",
    status: "స్థితి",
    monitoring: "పరిశీలనలో ఉంది",
    underTreatment: "చికిత్స జరుగుతోంది",
    recovering: "కోలుకుంటోంది",
    resolved: "నయమైంది",
    totalEntries: "మొత్తం రికార్డులు",
    searchJournal: "పంట, ఔషధం లేదా లక్షణం వెతకండి...",
    noEntriesFound: "జర్నల్ రికార్డులు లేవు",
    entrySaved: "నమోదు సేవ్ చేయబడింది",
    entryDeleted: "నమోదు తొలగించబడింది",
    filterAll: "అన్నీ",
    filterActive: "చికిత్సలో ఉన్నవి",
    filterResolved: "నయమైనవి",
    dosageRecommended: "సిఫార్సు చేసిన మోతాదు",
    notes: "గమనికలు",

    user: "వినియోగదారు",
    language: "భాష",
    languageSubtitle: "భాష / Language",
    selectLanguage: "భాషను ఎంచుకోండి",
    selectLanguageTitle: "భాషను ఎంచుకోండి / Select Language",
    chooseLanguageSub: "మీ ప్రాంతీయ భాషను ఎంచుకోండి",
    searchLanguage: "భాషను వెతకండి...",
    change: "మార్చు",
    allLanguages: "అన్ని భాషలు",
    southIndianLangs: "దక్షిణ భారతీయ భాషలు (4)",
    hindiAndNorth: "హిందీ & ఉత్తర",
    gujaratiAndMarathi: "గుజరాతీ & మరాఠీ",
    englishLang: "ఇంగ్లీష్",
    logout: "లాగ్ అవుట్",
    cancel: "రద్దు చేయి",
    save: "సేవ్ చేయి",
    edit: "సవరించు",
    delete: "తొలగించు",
    close: "మూసివేయి",
    back: "వెనుకకు",
    apply: "వర్తింపజేయి",
    search: "వెతకండి",
    loading: "లోడ్ అవుతోంది...",
    success: "విజయవంతం",
  },

  // Kannada (ಕನ್ನಡ)
  kn: {
    home: "ಮುಖಪುಟ",
    crop: "ಬೆಳೆಗಳು",
    videos: "ವೀಡಿಯೊಗಳು",
    journal: "ಜರ್ನಲ್",
    productivity: "ಉತ್ಪಾದಕತೆ",
    tasks: "ಕಾರ್ಯಗಳು",
    activity: "ಚಟುವಟಿಕೆ",
    settings: "ಸೆಟ್ಟಿಂಗ್ಸ್",

    welcomeBack: "ರೈತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    dashboardSubtitle: "ಸ್ಮಾರ್ಟ್ ಆಗ್ರೋಹೋಮಿಯೋಪತಿ ಮತ್ತು ಬೆಳೆ ನಿರ್ವಹಣಾ ಕೇಂದ್ರ",
    activeSeason: "🌱 ಪ್ರಸ್ತುತ ಋತು",
    totalCrops: "ಒಟ್ಟು ಬೆಳೆಗಳು",
    activeTreatments: "ಸಕ್ರಿಯ ಚಿಕಿತ್ಸೆಗಳು",
    healthyPlots: "ಆರೋಗ್ಯಕರ / ಗುಣಮುಖ",
    seasonalAdvisory: "ಸಿಂಪಡಣೆ ಸಮಯ ಮತ್ತು ಸಲಹೆ",
    bestSprayTime: "ಹೋಮಿಯೋಪತಿ ಸಿಂಪಡಣೆಗೆ ಮುಂಜಾನೆ ಅಥವಾ ಮುಸ್ಸಂಜೆ ಸಮಯ ಉತ್ತಮ. ಬಿಸಿಲಿನಲ್ಲಿ ಸಿಂಪಡಿಸಬೇಡಿ.",
    navigationHub: "ಕೃಷಿ ಕೇಂದ್ರ",
    cropGuide: "ಬೆಳೆ ಮಾರ್ಗದರ್ಶಿ",
    cultivationSubtitle: "ಬೇಸಾಯ, ಋತುಗಳು ಮತ್ತು ಆರೈಕೆ",
    myJournal: "ಕೃಷಿ ಜರ್ನಲ್",
    activeTreatmentsSubtitle: "ಸಕ್ರಿಯ ಚಿಕಿತ್ಸೆಗಳು ಮತ್ತು ದಾಖಲೆಗಳು",
    repertoryBook: "ರೋಗಗಳು ಮತ್ತು ಕೀಟಗಳು",
    repertorySubtitle: "ರೋಗ ಮತ್ತು ಕೀಟ ರೆಪರ್ಟರಿ",
    materiaEncyclopedia: "ಮೆಟೀರಿಯಾ ಮೆಡಿಕಾ",
    materiaSubtitle: "ಹೋಮಿಯೋಪತಿ ವಿವರಣೆ",
    quickRemedyFinder: "ತುರ್ತು ರೋಗಲಕ್ಷಣ ಪತ್ತೆ",
    openFinder: "ಹುಡುಕಿ →",
    featuredCrops: "ಪ್ರಮುಖ ಕಾಲೋಚಿತ ಬೆಳೆಗಳು",
    viewAll: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
    recentActivity: "ಇತ್ತೀಚಿನ ಕೃಷಿ ಚಿಕಿತ್ಸೆಗಳು",
    noRecentTreatments: "ಯಾವುದೇ ಸಕ್ರಿಯ ಚಿಕಿತ್ಸೆಗಳಿಲ್ಲ.",
    agroTipOfTheDay: "ಆಗ್ರೋಹೋಮಿಯೋಪತಿ ತತ್ವ",
    duration: "ಅವಧಿ",

    // Crop Names
    crop_tomato: "ಟೊಮ್ಯಾಟೊ",
    crop_potato: "ಆಲೂಗಡ್ಡೆ",
    crop_onion: "ಈರುಳ್ಳಿ & ಬೆಳ್ಳುಳ್ಳಿ",
    crop_chilli: "ಮೆಣಸಿನಕಾಯಿ & ಕ್ಯಾಪ್ಸಿಕಂ",
    crop_cauliflower_cabbage: "ಹೂಕೋಸು & ಎಲೆಕೋಸು",
    crop_wheat: "ಗೋಧಿ",
    crop_paddy_rice: "ಭತ್ತ / ಅಕ್ಕಿ",
    crop_maize: "ಮೆಕ್ಕೆಜೋಳ",
    crop_chickpea: "ಕಡಲೆ",
    crop_pigeonpea: "ತೊಗರಿ ಬೇಳೆ",
    crop_mango: "ಮಾವಿನ ಹಣ್ಣು",
    crop_banana: "ಬಾಳೆಹಣ್ಣು",
    crop_apple: "ಸೇಬು",
    crop_cotton: "ಹತ್ತಿ",
    crop_mustard: "ಸಾಸಿವೆ",
    crop_turmeric_ginger: "ಅರಿಶಿನ & ಶುಂಠಿ",
    crop_coriander: "ಕೊತ್ತಂಬರಿ",

    cropGuideTitle: "ಬೆಳೆ ಬೇಸಾಯ ಮತ್ತು ಆಗ್ರೋಹೋಮಿಯೋಪತಿ",
    cropGuideSubtitle: "ಬೆಳೆ ಋತುಗಳು, ಬಿತ್ತನೆ ವಿಧಾನಗಳು, ಮಣ್ಣಿನ ಅಗತ್ಯತೆಗಳು ಮತ್ತು ಹೋಮಿಯೋಪತಿ ಆರೈಕೆ.",
    searchCropsPlaceholder: "ಬೆಳೆ ಹೆಸರು, ಋತು, ಮಣ್ಣು ಅಥವಾ ಔಷಧಿ ಹುಡುಕಿ...",
    bestWayToGrow: "ಉತ್ತಮ ಬೇಸಾಯ ಪದ್ಧತಿಗಳು",
    growingRequirements: "ಬೆಳವಣಿಗೆಯ ಅಗತ್ಯಗಳು",
    homeopathyForCrop: "ಹೋಮಿಯೋಪತಿ ಆರೈಕೆ ಯೋಜನೆ",
    soilAndClimate: "ಮಣ್ಣು ಮತ್ತು ಹವಾಮಾನ",
    sowingAndSpacing: "ಬಿತ್ತನೆ ಮತ್ತು ಅಂತರ",
    waterAndNutrition: "ನೀರಾವರಿ ಮತ್ತು ಪೋಷಣೆ",
    harvestingInfo: "ಕೊಯ್ಲು ಮತ್ತು ಇಳುವರಿ",
    seedTreatment: "ಬೀಜೋಪಚಾರ",
    vegetativeStage: "ಸಸ್ಯೀಯ ಬೆಳವಣಿಗೆ",
    floweringStage: "ಹೂವು ಮತ್ತು ಕಾಯಿ ಕಟ್ಟುವ ಹಂತ",
    pestDefense: "ಕೀಟ ಮತ್ತು ರೋಗ ರಕ್ಷಣೆ",
    weatherStress: "ಹವಾಮಾನ ಒತ್ತಡ ನಿರ್ವಹಣೆ",
    doneViewing: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    logToJournal: "ಜರ್ನಲ್‌ನಲ್ಲಿ ದಾಖಲಿಸಿ",

    user: "ಬಳಕೆದಾರ",
    language: "ಭಾಷೆ",
    languageSubtitle: "ಭಾಷೆ / Language",
    selectLanguage: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    selectLanguageTitle: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ / Select Language",
    chooseLanguageSub: "ನಿಮ್ಮ ಪ್ರಾದೇಶಿಕ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    searchLanguage: "ಭಾಷೆ ಹುಡುಕಿ...",
    change: "ಬದಲಾಯಿಸಿ",
    allLanguages: "ಎಲ್ಲಾ ಭಾಷೆಗಳು",
    southIndianLangs: "ದಕ್ಷಿಣ ಭಾರತೀಯ ಭಾಷೆಗಳು (4)",
    hindiAndNorth: "ಹಿಂದಿ ಮತ್ತು ಉತ್ತರ",
    gujaratiAndMarathi: "ಗುಜರಾತಿ ಮತ್ತು ಮರಾಠಿ",
    englishLang: "ಇಂಗ್ಲಿಷ್",
    logout: "ಲಾಗ್ ಔಟ್",
    cancel: "ರದ್ದುಮಾಡಿ",
    save: "ಉಳಿಸಿ",
    edit: "ತಿದ್ದಿ",
    delete: "ಅಳಿಸಿ",
    close: "ಮುಚ್ಚಿ",
    back: "ಹಿಂದಕ್ಕೆ",
    apply: "ಅನ್ವಯಿಸು",
    search: "ಹುಡುಕಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    success: "ಯಶಸ್ವಿ",
  },

  // Malayalam (മലയാളം)
  ml: {
    home: "ഹോം",
    crop: "വിളകൾ",
    videos: "വീഡിയോകൾ",
    journal: "ജേണൽ",
    productivity: "ഉത്പാദനക്ഷമത",
    tasks: "ചുമതലകൾ",
    activity: "പ്രവർത്തനം",
    settings: "ക്രമീകരണങ്ങൾ",

    welcomeBack: "ഫാം ഡാഷ്‌ബോർഡ്",
    dashboardSubtitle: "സ്മാർട്ട് അഗ്രോഹോമിയോപ്പതി & വിള പരിപാലന കേന്ദ്രം",
    activeSeason: "🌱 നിലവിലെ സീസൺ",
    totalCrops: "ആകെ വിളകൾ",
    activeTreatments: "ചികിത്സയിലുള്ളവ",
    healthyPlots: "ആരോഗ്യമുള്ളവ / ഭേദമായവ",
    seasonalAdvisory: "തളിക്കൽ സമയവും നിർദ്ദേശങ്ങളും",
    bestSprayTime: "ഹോമിയോപ്പതി മരുന്നുകൾ അതിരാവിലെയോ വൈകുന്നേരമോ തളിക്കുക. കടുത്ത വെയിലിൽ തളിക്കരുത്.",
    navigationHub: "ഫാം ഹബ്ബ്",
    cropGuide: "വിള ഗൈഡ്",
    cultivationSubtitle: "കൃഷിരീതി, സീസൺ, പരിചരണം",
    myJournal: "ഫാം ജേണൽ",
    activeTreatmentsSubtitle: "ചികിത്സകളും രേഖകളും",
    repertoryBook: "രോഗങ്ങളും കീടങ്ങളും",
    repertorySubtitle: "രോഗ-കീട പ്രതിവിധി പട്ടിക",
    materiaEncyclopedia: "മെറ്റീരിയ മെഡിക്ക",
    materiaSubtitle: "ഹോമിയോപ്പതി വിവരണം",
    quickRemedyFinder: "ലക്ഷണ കണ്ടെത്തൽ",
    openFinder: "കണ്ടെത്തുക →",
    featuredCrops: "പ്രധാന സീസണൽ വിളകൾ",
    viewAll: "എല്ലാം കാണുക",
    recentActivity: "സമീപകാല ഫാം ചികിത്സകൾ",
    noRecentTreatments: "ചികിത്സയിലുള്ളവ ഒന്നുമില്ല.",
    agroTipOfTheDay: "അഗ്രോഹോമിയോപ്പതി തത്വം",
    duration: "കാലയളവ്",

    // Crop Names
    crop_tomato: "തക്കാളി",
    crop_potato: "ഉരുളക്കിഴങ്ങ്",
    crop_onion: "സവാള & വെളുത്തുള്ളി",
    crop_chilli: "മുളക് & കാപ്സിക്കം",
    crop_cauliflower_cabbage: "കാബേജ് & കോളിഫ്ലവർ",
    crop_wheat: "ഗോതമ്പ്",
    crop_paddy_rice: "നെല്ല് / അരി",
    crop_maize: "മക്കച്ചോളം",
    crop_chickpea: "കടല",
    crop_pigeonpea: "തുവര പരിപ്പ്",
    crop_mango: "മാങ്ങ",
    crop_banana: "വാഴപ്പഴം",
    crop_apple: "ആപ്പിൾ",
    crop_cotton: "പരുത്തി",
    crop_mustard: "കടുക്",
    crop_turmeric_ginger: "മഞ്ഞൾ & ഇഞ്ചി",
    crop_coriander: "മല്ലിയില",

    cropGuideTitle: "വിള കൃഷിയും അഗ്രോഹോമിയോപ്പതിയും",
    cropGuideSubtitle: "വിള സീസണുകൾ, നടീൽ രീതികൾ, മണ്ണിന്റെ ആവശ്യകതകൾ, ഹോമിയോപ്പതി പരിചരണം.",
    searchCropsPlaceholder: "വിളയുടെ പേര്, സീസൺ, മണ്ണ് അല്ലെങ്കിൽ മരുന്ന് തിരയുക...",
    bestWayToGrow: "മികച്ച കൃഷിരീതികൾ",
    growingRequirements: "വളർച്ചാ ആവശ്യങ്ങൾ",
    homeopathyForCrop: "ഹോമിയോപ്പതി സംരക്ഷണ പദ്ധതി",
    soilAndClimate: "മണ്ണും കാലാവസ്ഥയും",
    sowingAndSpacing: "നടീലും അകലവും",
    waterAndNutrition: "നനയും പോഷണവും",
    harvestingInfo: "വിളവെടുപ്പും ഉൽപാദനവും",
    seedTreatment: "വിത്ത് ചികിത്സ",
    vegetativeStage: "കായിക വളർച്ച",
    floweringStage: "പൂവിടലും കായ്ക്കലും",
    pestDefense: "കീട-രോഗ പ്രതിരോധം",
    weatherStress: "കാലാവസ്ഥാ സമ്മർദ്ദ പരിഹാരം",
    doneViewing: "പൂർത്തിയായി",
    logToJournal: "ജേണലിൽ രേഖപ്പെടുത്തുക",

    user: "ഉപയോക്താവ്",
    language: "ഭാഷ",
    languageSubtitle: "ഭാഷ / Language",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    selectLanguageTitle: "ഭാഷ തിരഞ്ഞെടുക്കുക / Select Language",
    chooseLanguageSub: "നിങ്ങളുടെ പ്രാദേശിക ഭാഷ തിരഞ്ഞെടുക്കുക",
    searchLanguage: "ഭാഷ തിരയുക...",
    change: "മാറ്റുക",
    allLanguages: "എല്ലാ ഭാഷകളും",
    southIndianLangs: "ദക്ഷിണേന്ത്യൻ ഭാഷകൾ (4)",
    hindiAndNorth: "ഹിന്ദിയും വടക്കും",
    gujaratiAndMarathi: "ഗുജറാത്തിയും മറാഠിയും",
    englishLang: "ഇംഗ്ലീഷ്",
    logout: "ലോഗ് ഔട്ട്",
    cancel: "റദ്ദാക്കുക",
    save: "സൂക്ഷിക്കുക",
    edit: "തിരുത്തുക",
    delete: "നീക്കംചെയ്യുക",
    close: "അടയ്ക്കുക",
    back: "പിന്നോട്ട്",
    apply: "ബാധകമാക്കുക",
    search: "തിരയുക",
    loading: "ലോഡ് ചെയ്യുന്നു...",
    success: "വിജയം",
  },

  // Bengali (বাংলা)
  bn: {
    home: "হোম",
    crop: "ফসল",
    videos: "ভিডিও",
    journal: "জার্নাল",
    productivity: "উৎপাদনশীলতা",
    tasks: "কাজ",
    activity: "কার্যকলাপ",
    settings: "সেটিংস",

    welcomeBack: "ফার্ম ড্যাশবোর্ড",
    dashboardSubtitle: "স্মার্ট এগ্রোহোমিওপ্যাথি এবং ফসল ব্যবস্থাপনা কেন্দ্র",
    activeSeason: "🌱 সক্রিয় মরশুম",
    totalCrops: "মোট ফসল",
    activeTreatments: "চিকিৎসাধীন",
    healthyPlots: "সুস্থ / নিরাময় হয়েছে",
    seasonalAdvisory: "স্প্রে করার সময় ও পরামর্শ",
    bestSprayTime: "ভোরবেলা বা সন্ধ্যায় হোমিওপ্যাথিক স্প্রে করা সবচেয়ে ভালো। তীব্র রোদে স্প্রে করবেন না।",
    navigationHub: "ফার্ম হাব",
    cropGuide: "ফসল গাইড",
    cultivationSubtitle: "চাষাবাদ, মরশুম ও পরিচর্যা",
    myJournal: "মাঠের জার্নাল",
    activeTreatmentsSubtitle: "চলমান চিকিৎসা ও লগ",
    repertoryBook: "রোগ ও কীটপতঙ্গ",
    repertorySubtitle: "রোগ ও পোকামাকড়ের রেপার্টরি",
    materiaEncyclopedia: "মেটেরিয়া মেডিকা",
    materiaSubtitle: "হোমিওপ্যাথিক বিবরণ",
    quickRemedyFinder: "জরুরী লক্ষণ নির্ণয়",
    openFinder: "খুঁজুন →",
    featuredCrops: "প্রধান মরশুমী ফসল",
    viewAll: "সব দেখুন",
    recentActivity: "সাম্প্রতিক মাঠের চিকিৎসা",
    noRecentTreatments: "বর্তমানে কোনো চিকিৎসাধীন ফসল নেই।",
    agroTipOfTheDay: "এগ্রোহোমিওপ্যাথি নীতি",
    duration: "সময়কাল",

    // Crop Names
    crop_tomato: "টমেটো",
    crop_potato: "আলু",
    crop_onion: "পেঁয়াজ ও রসুন",
    crop_chilli: "মরিচ ও ক্যাপসিকাম",
    crop_cauliflower_cabbage: "ফুলকপি ও বাঁধাকপি",
    crop_wheat: "গম",
    crop_paddy_rice: "ধান / চাল",
    crop_maize: "ভুট্টা",
    crop_chickpea: "ছোলা",
    crop_pigeonpea: "অড়হর ডাল",
    crop_mango: "আম",
    crop_banana: "কলা",
    crop_apple: "আপেল",
    crop_cotton: "তুলা",
    crop_mustard: "সরিষা",
    crop_turmeric_ginger: "হলুদ ও আদা",
    crop_coriander: "ধনেপাতা",

    cropGuideTitle: "ফসল চাষ ও এগ্রোহোমিওপ্যাথি",
    cropGuideSubtitle: "ফসলের মরশুম, বপন পদ্ধতি, মাটির চাহিদা ও হোমিওপ্যাথিক পরিচর্যা।",
    searchCropsPlaceholder: "ফসলের নাম, মরশুম, মাটি বা প্রতিকার খুঁজুন...",
    bestWayToGrow: "চাষের সেরা পদ্ধতি",
    growingRequirements: "বৃদ্ধির প্রয়োজনীয়তা",
    homeopathyForCrop: "হোমিওপ্যাথিক যত্ন পরিকল্পনা",
    soilAndClimate: "মাটি ও জলবায়ু",
    sowingAndSpacing: "বপন ও দূরত্ব",
    waterAndNutrition: "সেচ ও পুষ্টি",
    harvestingInfo: "ফসল কাটা ও ফলন",
    seedTreatment: "বীজ শোধন",
    vegetativeStage: "অঙ্গজ বৃদ্ধি",
    floweringStage: "ফুল ও ফল ধারণ",
    pestDefense: "কীটপতঙ্গ ও রোগ প্রতিরোধ",
    weatherStress: "আবহাওয়ার চাপ নিয়ন্ত্রণ",
    doneViewing: "সম্পন্ন",
    logToJournal: "জার্নালে যোগ করুন",

    user: "ব্যবহারকারী",
    language: "ভাষা",
    languageSubtitle: "ভাষা / Language",
    selectLanguage: "ভাষা নির্বাচন করুন",
    selectLanguageTitle: "ভাষা নির্বাচন করুন / Select Language",
    chooseLanguageSub: "আপনার পছন্দের আঞ্চলিক ভাষা বেছে নিন",
    searchLanguage: "ভাষা খুঁজুন...",
    change: "পরিবর্তন",
    allLanguages: "সমস্ত ভাষা",
    southIndianLangs: "দক্ষিণ ভারতীয় (4)",
    hindiAndNorth: "হিন্দি ও উত্তর",
    gujaratiAndMarathi: "গুজরাটি ও মারাঠি",
    englishLang: "ইংরেজি",
    logout: "লগ আউট",
    cancel: "বাতিল",
    save: "সংরক্ষণ",
    edit: "সম্পাদনা",
    delete: "মুছুন",
    close: "বন্ধ",
    back: "ফিরে যান",
    apply: "প্রয়োগ করুন",
    search: "অনুসন্ধান",
    loading: "লোড হচ্ছে...",
    success: "সফল",
  },

  // Punjabi (ਪੰਜਾਬੀ)
  pa: {
    home: "ਹੋਮ",
    crop: "ਫ਼ਸਲਾਂ",
    videos: "ਵੀਡੀਓ",
    journal: "ਜਰਨਲ",
    productivity: "ਉਤਪਾਦਕਤਾ",
    tasks: "ਕੰਮ",
    activity: "ਗਤੀਵਿਧੀ",
    settings: "ਸੈਟਿੰਗਾਂ",

    welcomeBack: "ਕਿਸਾਨ ਡੈਸ਼ਬੋਰਡ",
    dashboardSubtitle: "ਸਮਾਰਟ ਐਗਰੋਹੋਮਿਓਪੈਥੀ ਅਤੇ ਫ਼ਸਲ ਪ੍ਰਬੰਧਨ",
    activeSeason: "🌱 ਚੱਲ ਰਿਹਾ ਸੀਜ਼ਨ",
    totalCrops: "ਕੁੱਲ ਫ਼ਸਲਾਂ",
    activeTreatments: "ਇਲਾਜ ਅਧੀਨ",
    healthyPlots: "ਤੰਦਰੁਸਤ / ਠੀਕ ਹੋਏ",
    seasonalAdvisory: "ਸਪਰੇਅ ਦਾ ਸਮਾਂ ਅਤੇ ਸਲਾਹ",
    bestSprayTime: "ਹੋਮਿਓਪੈਥਿਕ ਸਪਰੇਅ ਸਵੇਰੇ ਜਾਂ ਸ਼ਾਮ ਨੂੰ ਕਰਨੀ ਸਭ ਤੋਂ ਵਧੀਆ ਹੈ। ਤੇਜ਼ ਧੁੱਪ ਵਿੱਚ ਸਪਰੇਅ ਨਾ ਕਰੋ।",
    navigationHub: "ਫ਼ਾਰਮ ਹੱਬ",
    cropGuide: "ਫ਼ਸਲ ਗਾਈਡ",
    cultivationSubtitle: "ਖੇਤੀ, ਮੌਸਮ ਅਤੇ ਦੇਖਭਾਲ",
    myJournal: "ਖੇਤ ਜਰਨਲ",
    activeTreatmentsSubtitle: "ਚੱਲ ਰਹੇ ਇਲਾਜ ਅਤੇ ਰਿਕਾਰਡ",
    repertoryBook: "ਬਿਮਾਰੀਆਂ ਅਤੇ ਕੀੜੇ",
    repertorySubtitle: "ਬਿਮਾਰੀਆਂ ਦੀ ਰੈਪਰਟਰੀ",
    materiaEncyclopedia: "ਮਟੀਰੀਆ ਮੈਡੀਕਾ",
    materiaSubtitle: "ਹੋਮਿਓਪੈਥਿਕ ਵੇਰਵਾ",
    quickRemedyFinder: "ਐਮਰਜੈਂਸੀ ਲੱਛਣ ਜਾਂਚ",
    openFinder: "ਲੱਭੋ →",
    featuredCrops: "ਮੁੱਖ ਮੌਸਮੀ ਫ਼ਸਲਾਂ",
    viewAll: "ਸਾਰੇ ਦੇਖੋ",
    recentActivity: "ਹਾਲੀਆ ਇਲਾਜ",
    noRecentTreatments: "ਕੋਈ ਸਰਗਰਮ ਇਲਾਜ ਨਹੀਂ ਹੈ।",
    agroTipOfTheDay: "ਐਗਰੋਹੋਮਿਓਪੈਥੀ ਸਿਧਾਂਤ",
    duration: "ਸਮਾਂ",

    // Crop Names
    crop_tomato: "ਟਮਾਟਰ",
    crop_potato: "ਆਲੂ",
    crop_onion: "ਪਿਆਜ਼ ਅਤੇ ਲਸਣ",
    crop_chilli: "ਮਿਰਚ ਅਤੇ ਸ਼ਿਮਲਾ ਮਿਰਚ",
    crop_cauliflower_cabbage: "ਫੁੱਲਗੋਭੀ ਅਤੇ ਬੰਦਗੋਭੀ",
    crop_wheat: "ਕਣਕ",
    crop_paddy_rice: "ਝੋਨਾ / ਚੌਲ",
    crop_maize: "ਮੱਕੀ",
    crop_chickpea: "ਛੋਲੇ",
    crop_pigeonpea: "ਅਰਹਰ ਦਾਲ",
    crop_mango: "ਅੰਬ",
    crop_banana: "ਕੇਲਾ",
    crop_apple: "ਸੇਬ",
    crop_cotton: "ਕਪਾਹ",
    crop_mustard: "ਸਰ੍ਹੋਂ",
    crop_turmeric_ginger: "ਹਲਦੀ ਅਤੇ ਅਦਰਕ",
    crop_coriander: "ਧਨੀਆ",

    cropGuideTitle: "ਫ਼ਸਲ ਉਤਪਾਦਨ ਅਤੇ ਐਗਰੋਹੋਮਿਓਪੈਥੀ",
    cropGuideSubtitle: "ਫ਼ਸਲ ਸੀਜ਼ਨ, ਬਿਜਾਈ ਦੇ ਤਰੀਕੇ, ਮਿੱਟੀ ਦੀ ਲੋੜ ਅਤੇ ਹੋਮਿਓਪੈਥਿਕ ਦੇਖਭਾਲ।",
    searchCropsPlaceholder: "ਫ਼ਸਲ ਦਾ ਨਾਮ, ਮੌਸਮ ਜਾਂ ਦਵਾਈ ਲੱਭੋ...",
    bestWayToGrow: "ਖੇਤੀ ਦੇ ਵਧੀਆ ਤਰੀਕੇ",
    growingRequirements: "ਉਗਾਉਣ ਦੀਆਂ ਲੋੜਾਂ",
    homeopathyForCrop: "ਹੋਮਿਓਪੈਥਿਕ ਇਲਾਜ ਯੋਜਨਾ",
    soilAndClimate: "ਮਿੱਟੀ ਅਤੇ ਮੌਸਮ",
    sowingAndSpacing: "ਬਿਜਾਈ ਅਤੇ ਦੂਰੀ",
    waterAndNutrition: "ਸਿੰਚਾਈ ਅਤੇ ਖੁਰਾਕ",
    harvestingInfo: "ਕਟਾਈ ਅਤੇ ਝਾੜ",
    seedTreatment: "ਬੀਜ ਸੋਧ",
    vegetativeStage: "ਸ਼ਾਖਾਵਾਂ ਦਾ ਵਾਧਾ",
    floweringStage: "ਫੁੱਲ ਅਤੇ ਫਲ ਬਣਨਾ",
    pestDefense: "ਕੀੜੇ ਅਤੇ ਬਿਮਾਰੀਆਂ ਤੋਂ ਬਚਾਅ",
    weatherStress: "ਮੌਸਮ ਦੇ ਤਣਾਅ ਤੋਂ ਰਾਹਤ",
    doneViewing: "ਮੁਕੰਮਲ",
    logToJournal: "ਜਰਨਲ ਵਿੱਚ ਦਰਜ ਕਰੋ",

    user: "ਵਰਤੋਂਕਾਰ",
    language: "ਭਾਸ਼ਾ",
    languageSubtitle: "ਭਾਸ਼ਾ / Language",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    selectLanguageTitle: "ਭਾਸ਼ਾ ਚੁਣੋ / Select Language",
    chooseLanguageSub: "ਆਪਣੀ ਪਸੰਦੀਦਾ ਖੇਤਰੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    searchLanguage: "ਭਾਸ਼ਾ ਲੱਭੋ...",
    change: "ਬਦਲੋ",
    allLanguages: "ਸਾਰੀਆਂ ਭਾਸ਼ਾਵਾਂ",
    southIndianLangs: "ਦੱਖਣੀ ਭਾਰਤੀ (4)",
    hindiAndNorth: "ਹਿੰਦੀ ਅਤੇ ਉੱਤਰ",
    gujaratiAndMarathi: "ਗੁਜਰਾਤੀ ਅਤੇ ਮਰਾਠੀ",
    englishLang: "ਅੰਗਰੇਜ਼ੀ",
    logout: "ਲਾਗ ਆਉਟ",
    cancel: "ਰੱਦ ਕਰੋ",
    save: "ਸੰਭਾਲੋ",
    edit: "ਸੋਧੋ",
    delete: "ਹਟਾਓ",
    close: "ਬੰਦ ਕਰੋ",
    back: "ਪਿੱਛੇ",
    apply: "ਲਾਗੂ ਕਰੋ",
    search: "ਖੋਜ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    success: "ਸਫਲਤਾ",
  },

  // Odia (ଓଡ଼ିଆ)
  or: {
    home: "ହୋମ୍",
    crop: "ଫସଲ",
    videos: "ଭିଡିଓ",
    journal: "ଜର୍ଣ୍ଣାଲ୍",
    productivity: "ଉତ୍ପାଦନଶୀଳତା",
    tasks: "କାର୍ଯ୍ୟ",
    activity: "କାର୍ଯ୍ୟକଳାପ",
    settings: "ସେଟିଂସ୍",

    welcomeBack: "ଫାର୍ମ ଡ୍ୟାସବୋର୍ଡ",
    dashboardSubtitle: "ସ୍ମାର୍ଟ ଏଗ୍ରୋହୋମିଓପାଥି ଏବଂ ଫସଲ ପରିଚାଳନା କେନ୍ଦ୍ର",
    activeSeason: "🌱 ଚାଲୁ ଋତୁ",
    totalCrops: "ମୋଟ ଫସଲ",
    activeTreatments: "ଚିକିତ୍ସାଧୀନ",
    healthyPlots: "ସୁସ୍ଥ / ଭଲ ହୋଇଥିବା",
    seasonalAdvisory: "ସ୍ପ୍ରେ କରିବା ସମୟ ଏବଂ ପରାମର୍ଶ",
    bestSprayTime: "ହୋମିଓପାଥିକ ସ୍ପ୍ରେ ସକାଳେ କିମ୍ବା ସନ୍ଧ୍ୟାରେ କରିବା ସର୍ବୋତ୍ତମ। ଟାଣ ଖରାରେ ସ୍ପ୍ରେ କରନ୍ତୁ ନାହିଁ।",
    navigationHub: "ଫାର୍ମ ହବ୍",
    cropGuide: "ଫସଲ ଗାଇଡ୍",
    cultivationSubtitle: "ଚାଷ, ଋତୁ ଏବଂ ଯତ୍ନ",
    myJournal: "ଜମି ଜର୍ଣ୍ଣାଲ୍",
    activeTreatmentsSubtitle: "ଚିକିତ୍ସା ଏବଂ ରେକର୍ଡ",
    repertoryBook: "ରୋଗ ଏବଂ କୀଟ",
    repertorySubtitle: "ରୋଗ ଏବଂ କୀଟପତଙ୍ଗ ରେପର୍ଟରୀ",
    materiaEncyclopedia: "ମ୍ୟାଟେରିଆ ମେଡିକା",
    materiaSubtitle: "ହୋମିଓପାଥିକ ବିବରଣୀ",
    quickRemedyFinder: "ଜରୁରୀ ଲକ୍ଷଣ ନିର୍ଣ୍ଣୟ",
    openFinder: "ଖୋଜନ୍ତୁ →",
    featuredCrops: "ପ୍ରମୁଖ ଋତୁକାଳୀନ ଫସଲ",
    viewAll: "ସବୁ ଦେଖନ୍ତୁ",
    recentActivity: "ସାମ୍ପ୍ରତିକ ଚିକିତ୍ସା",
    noRecentTreatments: "ବର୍ତ୍ତମାନ କୌଣସି ଚିକିତ୍ସାଧୀନ ଫସଲ ନାହିଁ।",
    agroTipOfTheDay: "ଏଗ୍ରୋହୋମିଓପାଥି ନୀତି",
    duration: "ଅବଧି",

    // Crop Names
    crop_tomato: "ଟମାଟୋ",
    crop_potato: "ଆଳୁ",
    crop_onion: "ପିଆଜ ଏବଂ ରସୁଣ",
    crop_chilli: "ଲଙ୍କା ଏବଂ କ୍ୟାପସିକମ",
    crop_cauliflower_cabbage: "ଫୁଲକୋବି ଏବଂ ବନ୍ଧାକୋବି",
    crop_wheat: "ଗହମ",
    crop_paddy_rice: "ଧାନ / ଚାଉଳ",
    crop_maize: "ମକା",
    crop_chickpea: "ବୁଟ / ଚଣା",
    crop_pigeonpea: "ହରଡ ଡାଲି",
    crop_mango: "ଆମ୍ବ",
    crop_banana: "କଦଳୀ",
    crop_apple: "ସେଓ",
    crop_cotton: "କପା",
    crop_mustard: "ସୋରିଷ",
    crop_turmeric_ginger: "ହଳଦୀ ଏବଂ ଅଦା",
    crop_coriander: "ଧନିଆ",

    cropGuideTitle: "ଫସଲ ଚାଷ ଏବଂ ଏଗ୍ରୋହୋମିଓପାଥି",
    cropGuideSubtitle: "ଫସଲ ଋତୁ, ବୁଣିବା ପଦ୍ଧତି, ମାଟିର ଆବଶ୍ୟକତା ଏବଂ ହୋମିଓପାଥିକ ଯତ୍ନ।",
    searchCropsPlaceholder: "ଫସଲ ନାମ, ଋତୁ, ମାଟି କିମ୍ବା ଔଷଧ ଖୋଜନ୍ତୁ...",
    bestWayToGrow: "ଚାଷର ଉତ୍ତମ ପଦ୍ଧତି",
    growingRequirements: "ବୃଦ୍ଧି ପାଇଁ ଆବଶ୍ୟକତା",
    homeopathyForCrop: "ହୋମିଓପାଥିକ ଯତ୍ନ ଯୋଜନା",
    soilAndClimate: "ମାଟି ଏବଂ ଜଳବାୟୁ",
    sowingAndSpacing: "ବୁଣିବା ଏବଂ ବ୍ୟବଧାନ",
    waterAndNutrition: "ଜଳସେଚନ ଏବଂ ପୋଷଣ",
    harvestingInfo: "ଅମଳ ଏବଂ ଉତ୍ପାଦନ",
    seedTreatment: "ବିହନ ବିଶୋଧନ",
    vegetativeStage: "ଶାଖା ପ୍ରଶାଖା ବୃଦ୍ଧି",
    floweringStage: "ଫୁଲ ଏବଂ ଫଳ ଧାରଣ",
    pestDefense: "କୀଟ ଏବଂ ରୋଗ ନିୟନ୍ତ୍ରଣ",
    weatherStress: "ପାଣିପାଗ ଚାପ ନିୟନ୍ତ୍ରଣ",
    doneViewing: "ସମାପ୍ତ",
    logToJournal: "ଜର୍ଣ୍ଣାଲରେ ଯୋଡନ୍ତୁ",

    user: "ବ୍ୟବହାରକାରୀ",
    language: "ଭାଷା",
    languageSubtitle: "ଭାଷା / Language",
    selectLanguage: "ଭାଷା ଚୟନ କରନ୍ତୁ",
    selectLanguageTitle: "ଭାଷା ଚୟନ କରନ୍ତୁ / Select Language",
    chooseLanguageSub: "ଆପଣଙ୍କ ପସନ୍ଦର ଆଞ୍ଚଳିକ ଭାଷା ବାଛନ୍ତୁ",
    searchLanguage: "ଭାଷା ଖୋଜନ୍ତୁ...",
    change: "ପରିବର୍ତ୍ତନ",
    allLanguages: "ସମସ୍ତ ଭାଷା",
    southIndianLangs: "ଦକ୍ଷିଣ ଭାରତୀୟ (4)",
    hindiAndNorth: "ହିନ୍ଦୀ ଏବଂ ଉତ୍ତର",
    gujaratiAndMarathi: "ଗୁଜରାଟୀ ଏବଂ ମରାଠୀ",
    englishLang: "ଇଂରାଜୀ",
    logout: "ଲଗ୍ ଆଉଟ୍",
    cancel: "ବାତିଲ୍",
    save: "ସଂରକ୍ଷଣ",
    edit: "ସମ୍ପାଦନ",
    delete: "ବିଲୋପ",
    close: "ବନ୍ଦ",
    back: "ପଛକୁ",
    apply: "ପ୍ରୟୋଗ",
    search: "ଖୋଜନ୍ତୁ",
    loading: "ଲୋଡ୍ ହେଉଛି...",
    success: "ସଫଳତା",
  },

  // Urdu (اردو)
  ur: {
    home: "ہوم",
    crop: "فصلیں",
    videos: "ویڈیوز",
    journal: "جرنل",
    productivity: "پیداواری صلاحیت",
    tasks: "کام",
    activity: "سرگرمی",
    settings: "ترتیبات",

    welcomeBack: "فارم ڈیش بورڈ",
    dashboardSubtitle: "سمارٹ ایگرو ہومیوپیتھی اور فصل کا انتظام",
    activeSeason: "🌱 فعال موسم",
    totalCrops: "کل فصلیں",
    activeTreatments: "زیر علاج",
    healthyPlots: "صحت مند / شفایاب",
    seasonalAdvisory: "سپرے کا وقت اور مشورہ",
    bestSprayTime: "ہومیوپیتھک سپرے صبح سویرے یا شام کو کرنا بہترین ہے۔ تیز دھوپ میں سپرے نہ کریں۔",
    navigationHub: "فارم نیویگیشن حب",
    cropGuide: "فصل گائیڈ",
    cultivationSubtitle: "کاشت، موسم اور دیکھ بھال",
    myJournal: "فارم جرنل",
    activeTreatmentsSubtitle: "زیر علاج اور ریکارڈز",
    repertoryBook: "امراض اور کیڑے",
    repertorySubtitle: "امراض و کیڑوں کی ریپرٹری",
    materiaEncyclopedia: "میটেরیا میڈیکا",
    materiaSubtitle: "ہومیوپیتھک مونوگراف",
    quickRemedyFinder: "ہنگامی علامت کی تشخیص",
    openFinder: "تلاش کریں →",
    featuredCrops: "اہم موسمی فصلیں",
    viewAll: "سب دیکھیں",
    recentActivity: "حالیہ فارم علاج",
    noRecentTreatments: "فی الحال کوئی زیر علاج فصل نہیں ہے۔",
    agroTipOfTheDay: "ایگرو ہومیوپیتھی اصول",
    duration: "مدت",

    // Crop Names
    crop_tomato: "ٹماٹر",
    crop_potato: "آلو",
    crop_onion: "پیاز اور لہسن",
    crop_chilli: "مرچ اور شملہ مرچ",
    crop_cauliflower_cabbage: "پھول گوبھی اور بند گوبھی",
    crop_wheat: "گندم",
    crop_paddy_rice: "دھان / چاول",
    crop_maize: "مکئی",
    crop_chickpea: "چنا",
    crop_pigeonpea: "ارہر دال",
    crop_mango: "آم",
    crop_banana: "کیلا",
    crop_apple: "سیب",
    crop_cotton: "کپاس",
    crop_mustard: "سرسوں",
    crop_turmeric_ginger: "ہلدی اور ادرک",
    crop_coriander: "دھنیا",

    cropGuideTitle: "فصل کی کاشت اور ایگرو ہومیوپیتھی",
    cropGuideSubtitle: "فصل کے موسم، بوائی کے طریقے، مٹی کی ضروریات اور ہومیوپیتھک دیکھ بھال۔",
    searchCropsPlaceholder: "فصل کا نام، موسم، مٹی یا علاج تلاش کریں...",
    bestWayToGrow: "کاشت کے بہترین طریقے",
    growingRequirements: "نشوونما کی ضروریات",
    homeopathyForCrop: "ہومیوپیتھک نگہداشت کا منصوبہ",
    soilAndClimate: "مٹی اور آب و ہوا",
    sowingAndSpacing: "بوائی اور فاصلہ",
    waterAndNutrition: "آبپاشی اور غذائیت",
    harvestingInfo: "کٹائی اور پیداوار",
    seedTreatment: "بیج کا علاج",
    vegetativeStage: "پودے کی نشوونما",
    floweringStage: "پھول اور پھل کا مرحلہ",
    pestDefense: "کیڑوں اور بیماریوں سے بچاؤ",
    weatherStress: "موسمی دباؤ سے نجات",
    doneViewing: "مکمل",
    logToJournal: "جرنل میں شامل کریں",

    user: "صارف",
    language: "زبان",
    languageSubtitle: "زبان / Language",
    selectLanguage: "زبان منتخب کریں",
    selectLanguageTitle: "زبان منتخب کریں / Select Language",
    chooseLanguageSub: "اپنی پسندیدہ علاقائی زبان منتخب کریں",
    searchLanguage: "زبان تلاش کریں...",
    change: "تبدیل کریں",
    allLanguages: "تمام زبانیں",
    southIndianLangs: "جنوبی ہندوستانی (4)",
    hindiAndNorth: "ہندی اور شمال",
    gujaratiAndMarathi: "گجراتی اور مراٹھی",
    englishLang: "انگریزی",
    logout: "لاگ آؤٹ",
    cancel: "منسوخ کریں",
    save: "محفوظ کریں",
    edit: "ترمیم کریں",
    delete: "حذف کریں",
    close: "بند کریں",
    back: "واپس",
    apply: "لاگو کریں",
    search: "تلاش کریں",
    loading: "لوڈ ہو رہا ہے...",
    success: "کامیابی",
  },
};

/**
 * Translate a key into the specified language with fallback to English
 * @param {string} key - The translation key
 * @param {string} langCode - Language code ('en', 'hi', 'gu', 'mr', 'ta', 'te', 'kn', 'ml', etc.)
 * @param {Object} [params] - Optional interpolation params e.g. { query: 'test', name: 'Hindi' }
 * @returns {string} - Translated text
 */
export function translate(key, langCode = "en", params = {}) {
  const dictionary = TRANSLATIONS[langCode] || TRANSLATIONS.en;
  let text = dictionary[key] ?? TRANSLATIONS.en[key] ?? key;

  if (params && typeof params === "object") {
    Object.keys(params).forEach((placeholder) => {
      text = text.replace(
        new RegExp(`\\{${placeholder}\\}`, "g"),
        String(params[placeholder])
      );
    });
  }

  return text;
}

export const t = translate;
